### ISSUE TITLE
RayTracing: Assert in phereShape::raycast()

### ISSUE THREAD

**Issue by andreasdr** [DanielChappuis/reactphysics3d#101]
Hi,

I have an raytracing assert that pops up from time to time.

ext/reactphysics3d/src/collision/shapes/SphereShape.cpp:87: virtual bool reactphysics3d::SphereShape::raycast(const reactphysics3d::Ray&, reactphysics3d::RaycastInfo&, reactphysics3d::ProxyShape*, reactphysics3d::MemoryAllocator&) const: Assertion `t >= decimal(0.0)' failed.

Many thanx and 

Best regards
Andreas

**Comment by DanielChappuis** [comment]
Hello,

Thanks for reporting this issue.

Are you able to post the values of the variables inside the SphereShape::raycast() method at the point where this assert occurs ? It would help a lot.

**Comment by andreasdr** [comment]
Hi, will do monday at latest. Thanx.

**Comment by andreasdr** [comment]
Hi, I was on vacation. Sorry for the delay.

Please see attached a "bt full" of this crash. It was done with -O1 as there were too less information with -O2.

See here:
- https://pastebin.com/Dr5fXszU

Seems like I have to do this even without optimizations as so many stuff is optimized out. Hmm.

**Comment by andreasdr** [comment]
Ooooh. Seems like I do ray tracing with NaNs. I will check.

**Comment by DanielChappuis** [comment]
Ok let met know.

**Comment by andreasdr** [comment]
Yes fixed my code, did not see this error again. You can close this isssue. Sorry for the noise.

**Comment by DanielChappuis** [comment]
No problem. I am closing the issue.
