### ISSUE TITLE
Transform scale for physical bodies

### ISSUE THREAD

**Issue by dolphineye** [DanielChappuis/reactphysics3d#103]
Hi,

We are considering the use of your library for one of our projects. Until today, everything seemed to produce the expected results, and since the API seems pretty straightforward, your library is a good choice given our needs.

In my experiments today, I wanted to use one of my object's world transformation matrix to perform a raycasting against its physical body. So, basically, I did this:

```cpp
// Our local transformation contains the translation, rotation and scale of our object
glm::mat4 worldTransform;

// We want to apply our world transform to the physical body
rp3d::Transform physicalBodyTransform;
physicalBodyTransform.setFromOpenGL(glm::value_ptr(worldTransform));
physicalBody->setTransform(physicalBodyTransform);
```

When doing this, the raycasting obviously gives me unexpected results. When I digged things a bit, I realized that `rp3d::Transform` internally stores a `rp3d::Vector3` and a `rp3d::Quaternion`. My math is a bit rusty, but unless mistaken, the quaternion can't be used to represent the object scaling, which means that my object's scaling is lost in the process. Am I missing something?

Thank you for your help !

**Comment by DanielChappuis** [comment]
As explained [here](https://gamedev.stackexchange.com/questions/90767/bullet-physics-scaling), ReactPhysics3D and many physics engines do not allow "scale" in their transforms. Moreover, in ReactPhysics3D, you cannot currently change the scaling factor of a collision shape after its creation.

**Comment by dolphineye** [comment]
Thanks for your answer. So, if I understand to your reply properly, changing the collision shape's local transform won't work either after it was created? If not, are there any plans to address that in a near future?

**Comment by DanielChappuis** [comment]
Currently, changing the ProxyShape local transform will reduce the distance between the CollisionShape and the body origin but it won't scale the size of the CollisionShape itself. I will try to implement a method to scale the collision shape.

**Comment by dolphineye** [comment]
Thanks.

**Comment by DanielChappuis** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make possible to scale a collision shape (event in real-time). Also make sure we can reuse a TriangleMesh, PolygonVertexArray with multiple ConvexMeshes, ConcaveTriangleMeshes. We should be able to set a given scaling factor on the collision shape.](https://trello.com/c/zRakKgCa/41-make-possible-to-scale-a-collision-shape-event-in-real-time-also-make-sure-we-can-reuse-a-trianglemesh-polygonvertexarray-with-m)

**Comment by DanielChappuis** [comment]
The version v0.8.0 of ReactPhysics3D has been released. In this version, it is now possible to change the size of the collision shapes after their creation. For instance, it is possible to change the half extents of a BoxShape with the BoxShape::setHalfExtents() method or change the radius of a SphereShape using the SphereShape::setRadius() method for instance.

Note that this version contains some public API changes. Please read carefully the change log before upgrading to this new version and do not hesitate to take a look at the user manual.

I am therefore closing this issue.

**Comment by dolphineye** [comment]
That's very cool! Thank you!
