### ISSUE TITLE
error C2536 :- cannot specify explicit initializer for arrays

### ISSUE THREAD

**Issue by shalinsirwani** [DanielChappuis/reactphysics3d#104]
Physics\reactphysics3d-0.7.1\src\collision\shapes\TriangleShape.cpp(50): error C2536: 'reactphysics3d::TriangleShape::reactphysics3d::TriangleShape::mFaces' : cannot specify explicit initializer for arrays

while compiling on vs12..

**Comment by DanielChappuis** [comment]
According to this [thread](https://stackoverflow.com/questions/27882915/cant-specify-explicit-initializer-for-arrays), it seems that this is a feature of C++11 that was not implemented in Visual Studio 2012-2013. I suggest to use a more recent version of Visual Studio and it should compile fine.

**Comment by shalinsirwani** [comment]
Is there any possibility to modify this code snippet on visual studio 2013 ??

**Comment by DanielChappuis** [comment]
Maybe you can try this solution: https://stackoverflow.com/questions/20894398/cannot-specify-explicit-initializer-for-arrays

**Comment by shalinsirwani** [comment]
Is there any implementation in this project to get input file ( xyz , .off , .ply , .stl , .obj , etc ). And provides output in file , ( If possible please provide reference to it )????

**Comment by DanielChappuis** [comment]
I do not understand what you are asking. Can please explain it with more details ?

**Comment by shalinsirwani** [comment]
I mean following are the two input file in .off format 

[0.off.txt](https://github.com/DanielChappuis/reactphysics3d/files/3565987/0.off.txt)
[90.off.txt](https://github.com/DanielChappuis/reactphysics3d/files/3565988/90.off.txt)

**Comment by DanielChappuis** [comment]
I know what are .off, .ply, .stl, .obj files. I just don't understand what do you mean by **output file** in your question ?

**Comment by shalinsirwani** [comment]
Hmm , in case of collision detection no output file will be generated..
That was written mistakenly.
So now if possible please provide sample implementation of input custom file with those format (off ,ply). And the resultant would be collision detected or not with given those two input files

**Comment by DanielChappuis** [comment]
I really don't understand what you are trying to do. ReactPhysics3D is a physics library. It cannot load directly 3D model files like .obj, .ply, ....  It's not a game engine. You have to do it yourself. You can see in the testbed application for instance. There, .obj files are loaded and then, ReactPhysics3D is used to create bodies from those files manually.

**Comment by DanielChappuis** [comment]
I am closing this issue. Do not hesitate to reopen it if needed.
