### ISSUE TITLE
Can we build this as a dll for Unity Engine?

### ISSUE THREAD

**Issue by Duotun** [DanielChappuis/reactphysics3d#109]
My thought is to build as a dll for Unity to obtain some useful functions to do the collision detentions. Can this work? Could you please give me some guides to this? Thank you very much!

**Comment by DanielChappuis** [comment]
ReactPhysics3D is written in C++ and I don't know if it can be used inside Unity. I have never used a C++ library from Unity and I am not sure I can really help you with that.

**Comment by andreasdr** [comment]
If you compile RP3D with the same compiler Unity uses it should work. I am curious. Why would someone want to do this?

C++ ABI is different across different compilers. You can't compile with MINGW/GCC and use it with MSC unless it is a C API.

**Comment by andreasdr** [comment]
BTW: I do compile RP3D with clang, gcc and msc. It works out of the box or needs minor adjustments.

**Comment by Duotun** [comment]
Thank you very much for your responses! Using Unity may save time for rendering and scene management and I want to test the difference between this detection technology and Unity's internal ones.

**Comment by DJLinux** [comment]
If UNITIY can use C libs (*.dll *.so) I build a C wrapper for Windows and Linux both 32 and 64-bit
https://www.freebasic.net/forum/viewtopic.php?f=14&t=27180
