### ISSUE TITLE
Two hinge joints at the same place / 2D hinge joint

### ISSUE THREAD

**Issue by Omroth** [DanielChappuis/reactphysics3d#112]
Hiya, love the engine.

I'd really like to have multiple hinge joints at the same place - is there an accepted way of doing that, like having a very small collision body between the two or something?

Thanks,
Ian

**Comment by DanielChappuis** [comment]
Hello.

Thanks for your feedback. I am not really sure I understand your question. What do you mean by "at the same place" ? Do you mean multiple hinge joints between the same bodies A and B ? Can you explain in more details ?

**Comment by Omroth** [comment]
Sorry, to be clearer - I'd like a joint with two degrees of freedom rather than one, but also with limits.

**Comment by DanielChappuis** [comment]
This is not possible yet. I plan to add add a custom joint but not in a near future.

**Comment by Omroth** [comment]
Ok, thanks.
