### ISSUE TITLE
User manual 0.7.1 section 10.7 -  example code has wrong shape type

### ISSUE THREAD

**Issue by SendSpams** [DanielChappuis/reactphysics3d#117]
In the example code under section 10.7 this is written:

```
// Create the sphere collision shape 
rp3d::decimal radius = rp3d::decimal(3.0) 
const rp3d::BoxShape shape(radius);
```

It says it wants to create a SphereShape but instead creates a BoxShape.
Also later on in the same example it uses `shape` like this: `proxyShape = body->addCollisionShape(&shape, transform, mass);` however `addCollisionShape` takes a non const pointer to shape so defining the shape as const won't compile.

**Comment by DanielChappuis** [comment]
Thanks a lot for reporting this. I will fix this for the next release of the library.

**Comment by DanielChappuis** [comment]
The version v0.8.0 of ReactPhysics3D has been released. The user manual has been updated and this issue is now fixed.

Thanks a lot for reporting this issue.
