### ISSUE TITLE
Object size orders of magnitude

### ISSUE THREAD

**Issue by aliasdevelopment** [DanielChappuis/reactphysics3d#120]
Lets say you got a 0.15 meter, 0.15 millimeter or a 0.15 unit object.

How many orders of magnitude does the engine support / being stable with respect to 0.15 units?

Can a 0.15 unit sized object collide against a 1500.0 unit sized object? 

Any limitations/stability issues to consider when scaling objects?

**Comment by DanielChappuis** [comment]
I don't know precisely. You will have to try. It might also depends on the collision shapes that are used.
Maybe a 0.15 unit object against an object of 1500.0 units is quite a big difference.
