### ISSUE TITLE
Add a way to iterate over rigid bodies

### ISSUE THREAD

**Issue by Silberklinge** [DanielChappuis/reactphysics3d#121]
This idea was originally brought up in https://github.com/DanielChappuis/reactphysics3d/issues/61#issuecomment-522256669, but I feel it deserves its own issue. There should really be a way to easily iterate over the bodies in a world. There are plenty of use-cases such as debug-rendering and serialization that would be so much easier to implement if a user didn't have to encapsulate a world instance in a wrapper struct and forward all the functions, just to book-keep the added bodies. The world classes already have a protected member containing the list of bodies, the only thing left to do is to expose a function that can be used to iterate over them, which could be something like the following:

    typedef const CollisionBody* ConstCollisionBodyPtr;
    inline const ConstCollisionBodyPtr* CollisionWorld::getCollisionBodies() const {
        if(mBodies.size() == 0)
            return nullptr;
        return &mBodies[0];
    }
    
    typedef const RigidBody* ConstRigidBodyPtr;
    inline const ConstRigidBodyPtr* DynamicsWorld::getRigidBodies() const {
        if(mRigidBodies.size() == 0)
            return nullptr;
        return &mRigidBodies[0];
    }

And an example of the usage would be something like:

    for(auto i = world->getRigidBodies(); i < world->getRigidBodies() + world->getNbRigidBodies(); ++i) {
        const rp3d::RigidBody& body = **i;
        // Do whatever with body
    }

**Comment by DanielChappuis** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make possible to iterate over rigid bodies and collision bodies of a PhysicsWorld](https://trello.com/c/TN5ac0Au/43-make-possible-to-iterate-over-rigid-bodies-and-collision-bodies-of-a-physicsworld)

**Comment by DanielChappuis** [comment]
Thanks a lot for your feedback. I will add this feature in the next release of the library.

Note that the RigidBody class inherits from the CollisionBody class and therefore a RigidBody is also a CollisionBody. However, I guess that in your example, the getCollisionBodies() method only returns bodies that are CollisionBody but not RigidBody right ?

**Comment by DanielChappuis** [comment]
The version v0.8.0 of ReactPhysics3D has been released. In this version, there is now a PhysicsWorld::getNbRigidBodies() and PhysicsWorld::getRigidBody() methods to make possible to iterate over rigid bodies and PhysicsWorld::getNbCollisionBodies() and PhysicsWorld::getCollisionBody() methods to make possible to iterate over collision bodies. 

Note that this version contains some public API changes. Please read carefully the change log before upgrading to this new version and do not hesitate to take a look at the user manual.

Thanks a lot for your feedback. I am now closing this issue.
