### ISSUE TITLE
the levelFlag in class Destination is never used

### ISSUE THREAD

**Issue by cloudwu** [DanielChappuis/reactphysics3d#122]
https://github.com/DanielChappuis/reactphysics3d/blob/develop/src/utils/Logger.h#L328

`levelFlag` is stored on constructor, but never be used. I guess we should check this flag before `Destination::write` . So that we can ignore some log levels when we new a Logger object.

**Comment by DanielChappuis** [comment]
Thanks a lot for reporting this. I will check that.

**Comment by DanielChappuis** [comment]
The version v0.8.0 of ReactPhysics3D has been released. In this version, this issue is now fixed.

Thanks a lot for reporting this issue.
