### ISSUE TITLE
Find body linear velocity for point other than COG

### ISSUE THREAD

**Issue by esppat** [DanielChappuis/reactphysics3d#128]
I wonder if there is a way to find the exact (linear) velocity of a point of a body, point which is not the COG. This because I think the COG of the rotating body is not on the rotation axis (in my particular case, of course).
Then, the exact linear velocity of a point of the body cannot be calculated knowing only the local position of the point, the COG position, and the linear and angular velocities (of the COG, I think). 
I can calculate this velocity by using its position difference between two frames, but I would like to find a better (a more direct) way to calculate this.
Any clue? 
Thanks a lot!

**Comment by DanielChappuis** [comment]
I am not sure if I really understand your question but if you want to know the linear velocity of any point P on a rigid body, it can be computed with:

<img src="http://www.sciweavers.org/tex2img.php?eq=%20%5Coverrightarrow%7BV_p%7D%20%3D%20%20%5Coverrightarrow%7BV_C%7D%20%2B%20%20%5Coverrightarrow%7B%5Comega%7D%20%5Ctimes%20%5Coverrightarrow%7BCP%7D&bc=White&fc=Black&im=png&fs=12&ff=arev&edit=0" align="center" border="0" alt=" \overrightarrow{V_p} =  \overrightarrow{V_C} +  \overrightarrow{\omega} \times \overrightarrow{CP}" width="150" height="31" />

It can be read as the velocity of any point P on a rigid body is the linear velocity of the center of mass C + the cross product of the angular velocity of the body and the vector from C to P.

Is that what your requested ?

**Comment by esppat** [comment]
Hi Daniel,
No, this is not what I am looking for.
In your calculation, you suppose the COG is on the rotation axis. What if it is not the case? Imagine a wheel rolling on the floor: does the linear velocity of the COG plus the angular velocity express exactly the movement of the body in ReactPhysics3d?
Thanks a lot for your explanations
Patrice

**Comment by DanielChappuis** [comment]
I am not sure I really understand. When a wheel is rolling on the floor it is rotating around a rotation axis that is going through the center of mass if we consider a perfectly symmetrical wheel isn't it ? And yes it this case, the velocity of any point on the wheel can be expressed with the formula above.

**Comment by esppat** [comment]
OK, your last sentence is the answer I was looking for! :)
Thanks a lot
