### ISSUE TITLE
Material linking question

### ISSUE THREAD

**Issue by bolom009** [DanielChappuis/reactphysics3d#129]
As i understand material (friction, bounciness) linked to rigidbody in this library. Not sure why it not linked to the shape (cube, sphere, capsule etc.)? Other 3D physic engines (unity3d or box2d) linked material to the collider not rigid body, because one rigidbody can handle different colliders rigidBody->AddCollisionShape(shape).

**Comment by DanielChappuis** [comment]
Yes that's right. I have already changed this as you can see in the "[develop](https://github.com/DanielChappuis/reactphysics3d/tree/develop)" branch. This will be part of the next release of the library (v0.8.0).

**Comment by bolom009** [comment]
Cool, thanks for the answer :)

**Comment by DanielChappuis** [comment]
The version v0.8.0 of ReactPhysics3D has been released. In this version, the Material is now associated with a Collider and not a Rigid Body anymore.

Note that this version contains some public API changes. Please read carefully the change log before upgrading to this new version and do not hesitate to take a look at the user manual.

Thanks a lot for your feedback.
