### ISSUE TITLE
AngularDamping seems unable to stop a rotating Sphere

### ISSUE THREAD

**Issue by jagoly** [DanielChappuis/reactphysics3d#13]
As title, it seems that a RigidBody with only a ShapeSphere will never stop spinning due to only AngularDamping. The damping is working, in that it slows fast-spinning spheres, but only to a certain point. This is difficult to explain, but you can see the effects by placing some spheres with 0 friction on to a large surface with also 0 friction and moving them. They will move until they gradually stop due to VelocityDamping, but they will never stop spinning. In fact, they always seem to settle on specific spinning speed unrelated to what you actually have AngularDamping set to. 

This issue can also be seen when you do have friction on, where spheres will instead roll forever at the same constant speed. Am I missing something, or is this a bug / not yet implemented feature?

**Comment by DanielChappuis** [comment]
Thanks a lot. I will check this.

**Comment by DanielChappuis** [comment]
In the version 0.6.0 of ReactPhysics3D, support of rolling resistance has been added. It can be used to stop rolling shapes on a flat surface.
