### ISSUE TITLE
User manual correction concerning rp3d::TriangleVertexArray enums

### ISSUE THREAD

**Issue by Silberklinge** [DanielChappuis/reactphysics3d#131]
In [this](https://www.reactphysics3d.com/usermanual.html#x1-4300010.5) section of the user manual, the code example uses `rp3d::TriangleVertexArray::VERTEX_FLOAT_TYPE` and `rp3d::TriangleVertexArray::INDEX_INTEGER_TYPE`. However, using those expressions emits a compiler error because [the enums are declared as `enum class`](https://github.com/DanielChappuis/reactphysics3d/blob/f9fa2a227c484e7755eaad163525e0ebb42a61d1/src/collision/TriangleVertexArray.h#L52). They should be corrected to `rp3d::TriangleVertexArray::VertexDataType::VERTEX_FLOAT_TYPE` and `rp3d::TriangleVertexArray::IndexDataType::INDEX_INTEGER_TYPE`, respectively.

**Comment by DanielChappuis** [comment]
Thanks a lot for reporting this.
This will be fixed in the next release of the library.

**Comment by DanielChappuis** [comment]
The version v0.8.0 of ReactPhysics3D has been released. The user manual has been updated and this issue is now fixed.

Thanks a lot for reporting this issue.
