### ISSUE TITLE
Character like UE4 Character

### ISSUE THREAD

**Issue by KorolevSoftware** [DanielChappuis/reactphysics3d#132]
Hello, how I can create Character? In documentation write "A kinematic body does not collide
with other static or kinematic bodies."

**Comment by DanielChappuis** [comment]
Hello.

I am not very familiar with UE4 Character. Can you please explain what you would like to do ?

**Comment by KorolevSoftware** [comment]
Ok sorry. This is Player or NPS, they has capsule collision and can move by vector(velocity). Capsule collide with static, kinematic and dynamic bodies.
And capsule oriented always up.

I try create simple fps shooter liked quake, counter strike. And I need player controller.

**Comment by rentorious** [comment]
Something like this would be useful for me too
