### ISSUE TITLE
CMake improvements

### ISSUE THREAD

**Issue by micrenda** [DanielChappuis/reactphysics3d#135]
I am opening this ticket to suggest two improvements on the current CMake implementation.

1) Current CMake does not preserve the include directory structure on install
2) When using the CMake RP3D_DOUBLE_PRECISION_ENABLED flag, then we need to use -DIS_DOUBLE_PRECISION_ENABLED in our custom projects (it should be transparent to us).
3) There is no `FindRp3d.cmake` ready to be used

I took the freedom suggrest a fix for these three points.
Regards

**Comment by HugoPeters1024** [comment]
I believe issue 1. was already resolved since #125. It has not been released yet so you have to compile the master branch.

**Comment by DanielChappuis** [comment]
Thanks for your feedback. Yes, issue 1 is already fixed in the master branch. It will be part of the next released version of the library. I will try to include the fix for the two other issue in the next release as well.

**Comment by DanielChappuis** [comment]
The version v0.8.0 of ReactPhysics3D has been released. In this version, modern CMake is used and the issues above have been fixed.

Note that this version contains some public API changes. Please read carefully the change log before upgrading to this new version and do not hesitate to take a look at the user manual.

Thanks a lot for reporting those issues.
