### ISSUE TITLE
addCollisionShape documentation in .cpp is incorrect

### ISSUE THREAD

**Issue by Matt-Cummins** [DanielChappuis/reactphysics3d#139]
From RigidBody.cpp for RigidBody::addCollisionShape:

```
/// When you add a collision shape to the body, an internal copy of this
/// collision shape will be created internally. Therefore, you can delete it
/// right after calling this method or use it later to add it to another body.
```

This is contrary to the HTML documentation, which states that only a pointer is copied in:

```
First note that when you add a collision shape to a body, the shape will not be copied internally. You only give a pointer to the shape in parameter. The shape must exist during the whole lifetime of the body.
```

which is the actual behaviour.

**Comment by DanielChappuis** [comment]
That's right. I will fix this in the next release of the library.
Thanks a lot !

**Comment by DanielChappuis** [comment]
The version v0.8.0 of ReactPhysics3D has been released. In this version, this issue is now fixed.

Thanks a lot for reporting this issue.
