### ISSUE TITLE
Documentation for RigidBody::getContactManifoldsList() appears to be incorrect

### ISSUE THREAD

**Issue by kix-mcotton** [DanielChappuis/reactphysics3d#142]
I'm trying to get a list of contacts from a rigid body but the given code for this does not compile.

>     const ContactManifoldListElement* listElem; 
>     listElem = rigidBody->getContactManifoldsList(); 
>  
>     // For each contact manifold of the body 
>     for (; listElem != nullptr; listElem = listElem->next) { 
>         ContactManifold* manifold = listElem->contactManifold; 
>  
>         // For each contact point of the manifold 
>         for (int i=0; i<manifold->getNbContactPoints(); i++) { 
>  
>             // Get the contact point 
>             ContactPoint* point = manifold->getContactPoint(i); 
>  
>             // Get the world-space contact point on body 1 
>             Vector3 pos = point->getWorldPointOnBody1(); 
>  
>             // Get the world-space contact normal 
>             Vector3 normal = point->getNormal(); 
>         } 
>     }

`next` and `contactManifold` do not exist on the list element. There IS `getNext()` and `getContactManifold()` but I cannot use them because they are non const and `getContactManifoldsList()` returns a const pointer.

**Comment by HugoPeters1024** [comment]
Perhaps not very helpful in the larger scale but as temporary workaround, you can cast it to a non const pointer to bypass the compiler. I can imagine that the function can be marked as const without any changes, I'll see if that's the case.

**Comment by DanielChappuis** [comment]
Thanks for your feedback. You are right this part of the documentation doesn't really seem up to date.

I suggest to solve your issue as suggested by @HugoPeters1024. 

Note that in the next release of the library, retrieving the contacts will be a bit different (you will have to use the EventListener class for that). I will also update the documentation when it's released.

**Comment by kix-mcotton** [comment]
I was able to modify the code and add const to the methods mentioned. Which seems to be working fine without any side effects. Will be moving forward with that solution for now.
Thanks!

**Comment by DanielChappuis** [comment]
Ok perfect. I am closing this issue.
