### ISSUE TITLE
React won't build with VS or MinGW

### ISSUE THREAD

**Issue by loopahnoob** [DanielChappuis/reactphysics3d#145]
I've tried to build React using CMake without success. I used both Visual Studio (2015 & 2019) and MinGW (GCC) compilers to build the source code.

Here are the logs(MinGW has no errors in it's log, errors display in cmd although I specified it to write to the log): 

[ErrorLogs.zip](https://github.com/DanielChappuis/reactphysics3d/files/4607766/ErrorLogs.zip)

The VS log is too big (29MB) so I put both logs in the ZIP file.

**Comment by DanielChappuis** [comment]
Hello,

In you MinGW log, you can see that the ReactPhysics3D library is correctly builded. Then it tries to compile the testbed application (with demos) and then no more logs.

First, do you really need to compile the testbed application ? If you only need to compile the ReactPhysics3D library then you can uncheck the "RP3D_COMPILE_TESTBED" option in CMAKE and you should be fine.

However, if you need to compile the testbed application, it will need to compile the nanogui library that requires GLFW (for OpenGL) to be installed. If GLFW is not installed and you have asked to compile the testbed application, you should have errors when using ccmake command when you configure the cmake build.

About Visual Studio 2014, I am not sure it fully support C++ 11. Remember that ReactPhysics3D has to be compiled with C++ 11.

In you Visual Studio log, there are also errors about OpenGL functions not found. Is GLFW missing ?

**Comment by loopahnoob** [comment]
GLFW is installed in my MinGW directory, but I didn't install it in VS since I only used VS to try and build Bullet to no avail(the documentation of Bullet is very vague). 

Does the GLFW dll need to be installed in the MinGW directory as well? I installed it in System32 so I have no problems using my compiled app without recompiling.

**Comment by DanielChappuis** [comment]
You can install it anywhere as long as CMAKE is able to find it. If CMAKE cannot find it, you can specify in the CMAKE configurator where to find it.

**Comment by loopahnoob** [comment]
I've gotten React to work, thanks for your help! :D

**Comment by DanielChappuis** [comment]
Perfect. Good news !!
