### ISSUE TITLE
Calling glfwCreateWindow will give an Assertion fail at Quaternion.h

### ISSUE THREAD

**Issue by loopahnoob** [DanielChappuis/reactphysics3d#146]
[test.cpp.txt](https://github.com/DanielChappuis/reactphysics3d/files/4619595/test.cpp.txt)

Remove the ".txt".

Error:

Assertion failed!

Program: C:\Users\___\Desktop\Others\cpp\OpenGL\GLFW\GE\text.exe
File: C:/Users/___/Desktop/C++/reactphysics3d-0.7.1/src/mathematics/Quaternion.h, Line 266

Expression: lengthQuaternion > MACHINE_EPSILON

I don't know if this is related or not but C++/reactphysics3d-0.7.1 was already deleted. G++ might still be using that header instead of the same header in the MinGW include directory.

**Comment by DanielChappuis** [comment]
Can I ask you to post the whole stack trace when the assert occurs ?

**Comment by loopahnoob** [comment]
Wait, I'm sorry. This error was entirely related to the g++ error I had when running the program, reinstalling MinGW made the program work.

**Comment by DanielChappuis** [comment]
Ok I am glad to you have solved your issue.
