### ISSUE TITLE
Missing const

### ISSUE THREAD

**Issue by manuel5975p** [DanielChappuis/reactphysics3d#154]
```cpp
void PhysicsWorld::setGravity(Vector3& gravity);
```
takes in a mutable reference where that isn't necessary. This causes lines such as
```cpp
world->setGravity(Vector3(0,0,1));
```
to break.
It would be a lot cooler if there was a const on lines
`PhysicsWorld.h : 402`
and
`PhysicsWorld.cpp : 978`

**Comment by DanielChappuis** [comment]
Of course, you are right.

I have made the change in this [commit ](https://github.com/DanielChappuis/reactphysics3d/commit/fa05e1561eea366a47e601663ea0af07f031aee1)in the "master" branch.

Thanks a lot for reporting this.
