### ISSUE TITLE
Typo in CollisionShape.h

### ISSUE THREAD

**Issue by LopkyTonk** [DanielChappuis/reactphysics3d#159]
In file **CollisionShape.h** on line 167 there's typo: `friend class PhyscisWorld;` should be `friend class PhysicsWorld;`

**Comment by DanielChappuis** [comment]
Thanks a lot for taking the time to report this issue.

I have removed this declaration because it didn't seem to be used anymore.

This has been fixed with this [commit](https://github.com/DanielChappuis/reactphysics3d/commit/e7d9e106e92584013b76c4f08269615557687496) in the master branch
