### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by brizzly** [DanielChappuis/reactphysics3d#163]
Replace :
// Create the polygon vertex array 
Polygon**a**VertexArray* polygonVertexArray = new PolygonVertexArray(8, vertices, 3 **x** sizeof(float), 

With:
// Create the polygon vertex array 
PolygonVertexArray* polygonVertexArray = new PolygonVertexArray(8, vertices, 3 * sizeof(float),

**Comment by DanielChappuis** [comment]
Thanks a lot for this contribution.

I have pushed a fix in this [commit](https://github.com/DanielChappuis/reactphysics3d/commit/d464c7f8fb4d9acc32d7faef8a3c1f9909aa2c82) in the "develop" branch.
This will be uploaded online when the next version of the library is released.
