### ISSUE TITLE
Getting all objects inside specific area

### ISSUE THREAD

**Issue by MFridlyand** [DanielChappuis/reactphysics3d#168]
I need to find all objects which are inside some volume(sphere, frustum). How do it with reactphysics3d?

**Comment by DanielChappuis** [comment]
Hello.

You should take a look at the PhysicsWorld::testOverlap(...) methods. 
You will find the API reference [here](https://reactphysics3d.com/documentation/api/html/index.html) if you want to know more about those methods.

I hope this helps.

**Comment by DanielChappuis** [comment]
Has your question been answered ? Can I close this issue ?
