### ISSUE TITLE
Issues with convex mesh. assert(maxDotProduct >= decimal(0.0)) fails.

### ISSUE THREAD

**Issue by DEFAULTSAAS** [DanielChappuis/reactphysics3d#171]
I have been attempting to make a convex mesh shape, both using full faces and triangle faces, with this error occurring with both of them. It occurs when another rigid-body collides with the convex mesh shape. The convex mesh shape's rigid-body is static.

Here is the code:
```CPP
reactphysics3d::Transform TempTransform(reactphysics3d::Transform(reactphysics3d::Vector3(0.0f,0.0f,0.0f),reactphysics3d::Quaternion(0.0f,0.0f,0.0f,1.0f)));
//reactphysics3d::Transform TempTransform(DFEPhysicsTransform::DFETransformToRPT(*LevelMeshes[i]->MeshTransform));

reactphysics3d::PolygonVertexArray::PolygonFace* PolygonFaces = new reactphysics3d::PolygonVertexArray::PolygonFace[TempPhysicsMesh->GetTriangleCount()];
reactphysics3d::PolygonVertexArray::PolygonFace* Face = PolygonFaces;

for (int i = 0; i < TempPhysicsMesh->GetTriangleCount(); i++)
{
	Face->indexBase = i * 3;
	Face->nbVertices = 3;
	Face++;
}

// FaceVertices contains all the vertices loaded from a .obj file (non-triangulated).
// AltVertexIndices, contains the indices for the mesh (triangulated). 

reactphysics3d::PolygonVertexArray* PolygonVertexArray = new reactphysics3d::PolygonVertexArray(TempPhysicsMesh->GetVerticesCount(), &(TempPhysicsMesh->FaceVertices[0]), 3 * sizeof(float), &(TempPhysicsMesh->AltVertexIndices[0]), sizeof(unsigned int), TempPhysicsMesh->GetTriangleCount(), PolygonFaces, reactphysics3d::PolygonVertexArray::VertexDataType::VERTEX_FLOAT_TYPE,reactphysics3d::PolygonVertexArray::IndexDataType::INDEX_INTEGER_TYPE);
reactphysics3d::PolyhedronMesh* PolyhedronMesh = SystemGlobalVars->GlobalPhysicsCommon->createPolyhedronMesh(PolygonVertexArray);
TempPhysicsMesh->SetupPhysicsMesh(TempTransform,RPCS_ConvexMeshShape,DFECollisionShapeParams::SetConvexMeshShapeData(PolyhedronMesh, DFEPhysicsTransform::GlmVec3ToVector3(std::get<glm::vec3>(ConvU::DecodeVector(6, 3, TempEntityData[j].second)))), TempDataItems[3].DecodeInt(), DFEPOCM_ALL, SystemGlobalVars->GlobalPhysicsWorld, SystemGlobalVars->GlobalPhysicsCommon);
```

I have also tried using pre-triangulated .obj files, but get the same result. I use Blender to export models.

These vertices and indices work perfectly with the concave shape, so I do not understand what is going wrong.

Here is the code for the concave mesh.
```CPP

reactphysics3d::Transform TempTransform(DFEPhysicsTransform::DFETransformToRPT(*LevelMeshes[i]->MeshTransform));

for (int i = 0, Counter = 0; i < TempPhysicsMesh->FaceVertices.size(); i++)
{
	if (Counter == 3)
	{
		Counter = 0;
	}
	TempPhysicsMesh->FaceVertices[i] -= TempPhysicsMesh->GetFinalWorldPos()[Counter];
	Counter++;
} // Simply converts the vertices from world space to local space. I have found that doing this with the convex mesh shape, means that it won't be in the correct position.

//reactphysics3d::TriangleVertexArray* triangleArray = new reactphysics3d::TriangleVertexArray(TempPhysicsMesh->GetVerticesCount(),&(TempPhysicsMesh->Vertices[0]),5 * sizeof(float), &(TempPhysicsMesh->VertexNormals[0]),3 * sizeof(float),TempPhysicsMesh->GetTriangleCount(), &(TempPhysicsMesh->Indices[0]),3 * sizeof(int), reactphysics3d::TriangleVertexArray::VertexDataType::VERTEX_FLOAT_TYPE, reactphysics3d::TriangleVertexArray::NormalDataType::NORMAL_FLOAT_TYPE, reactphysics3d::TriangleVertexArray::IndexDataType::INDEX_INTEGER_TYPE);
reactphysics3d::TriangleVertexArray* triangleArray = new reactphysics3d::TriangleVertexArray(TempPhysicsMesh->GetVerticesCount(), &(TempPhysicsMesh->FaceVertices[0]), 3 * sizeof(float), TempPhysicsMesh->GetTriangleCount(), &(TempPhysicsMesh->AltVertexIndices[0]), 3 * sizeof(unsigned int), reactphysics3d::TriangleVertexArray::VertexDataType::VERTEX_FLOAT_TYPE, reactphysics3d::TriangleVertexArray::IndexDataType::INDEX_INTEGER_TYPE);
reactphysics3d::TriangleMesh* triangleMesh = SystemGlobalVars->GlobalPhysicsCommon->createTriangleMesh();
triangleMesh->addSubpart(triangleArray);

TempPhysicsMesh->SetupPhysicsMesh(TempTransform, RPCS_ConcaveMeshShape, DFECollisionShapeParams::SetConcaveMeshShapeData(triangleMesh, DFEPhysicsTransform::GlmVec3ToVector3(std::get<glm::vec3>(ConvU::DecodeVector(6, 3, TempEntityData[j].second)))), TempDataItems[3].DecodeInt(), DFEPOCM_ALL, SystemGlobalVars->GlobalPhysicsWorld, SystemGlobalVars->GlobalPhysicsCommon);

```

I have made some modifications to the library, however, these are all related to user data, and not anything else. I do use an event listener, but I have also tried disabling that and it still doesn't work. All other collision shapes work perfectly though, and I have enjoyed using the library with my game engine.

Thanks for your help.

The algorithm I use to get the triangulated indices:
```CPP
for (int i = 0,IndexOffset = 0; i < FaceSizes.size(); i++)
{ // FaceSizes contains the sizes of each face of the mesh.
 // The VertexIndices are the ones directly from the .obj file, so they are adjusted to be zero based.
	for (int j = 0; j < (FaceSizes[i] - 2); j++)
	{
		AltVertexIndices.push_back((VertexIndices[IndexOffset]) - 1);
		AltVertexIndices.push_back((VertexIndices[IndexOffset + 1 + j]) - 1);
		AltVertexIndices.push_back((VertexIndices[IndexOffset + 2 + j]) - 1);
	}
	IndexOffset += FaceSizes[i];
}
```
The vertices of the cube:

-10.502, -1, 1,
-10.502, 1, 1,
-10.502, -1, -1,
-10.502, 1, -1,
-8.50205, -1, 1,
-8.50205, 1, 1,
-8.50205, -1, -1,
-8.50205, 1, -1,

The indices of the cube:

1, 2, 0,
3, 6, 2,
7, 4, 6,
5, 0, 4,
6, 0, 2,
3, 5, 7,
1, 3, 2,
3, 7, 6,

Image of what occures:
![ConvexMeshShapeError](https://user-images.githubusercontent.com/32699618/93148636-3deedb00-f6ec-11ea-9b69-fdaab87d8d56.png)

**Comment by DEFAULTSAAS** [comment]
When the disabling the assertion, and using whole faces rather than triangulated ones, the collision seems to work perfectly.

**Comment by DanielChappuis** [comment]
Thanks for taking the time to report this.

Can I ask you to compile the ReactPhysics3D library in Debug mode and post here a complete stack trace when the assert occurs ?

**Comment by DEFAULTSAAS** [comment]
Unfortunately I can no longer reproduce the error; the assertion no longer fails. If it does fail again though, I will make sure to post the complete stack trace here.

**Comment by DanielChappuis** [comment]
Ok thanks !

**Comment by franciscotv** [comment]
> I have been attempting to make a convex mesh shape, both using full faces and triangle faces, with this error occurring with both of them. It occurs when another rigid-body collides with the convex mesh shape. The convex mesh shape's rigid-body is static.

The asssertion you mention can happen for several reasons, the dot product of the vectors:
- is zero if the vectors are perpendicular, or if one of the vectors or both of them are zero.
- is negative if the angle between the vectors is obtuse (90, 180)

are you sure your vectors are not below these conditions?, if so, the assertion is expected to throw.

**Comment by DEFAULTSAAS** [comment]
I think the issue was due to the vertex normal's being calculated incorrectly. 

I know with the concave mesh shape, that I have to specify my own vertex normal's during creation, otherwise a different assertion fails (I think is was due to an angle being above or below a threshold). 
With my own vertex normal's however, the concave mesh shape works perfectly; even thought at lower update rates, the rigid bodies do fall through it sometimes. It is complex terrain though, which it is not meant to be used for.

When it comes to the convex mesh shape, I passed in different vertices and indices at creation, which were in a slightly different order, and it worked fine. I don't know if the library expects them to be in a specific way; they were set up so the faces would be on the outside.

**Comment by DanielChappuis** [comment]
> When it comes to the convex mesh shape, I passed in different vertices and indices at creation, which were in a slightly different order, and it worked fine. I don't know if the library expects them to be in a specific way; they were set up so the faces would be on the outside.

 You can find some information [here](https://reactphysics3d.com/usermanual.html#x1-5000011.1.4) in the user manual that explains how to create a ConvexMeshShape.

Can I close this issue or is there still something wrong ?

**Comment by DEFAULTSAAS** [comment]
Indeed. There is no longer any issues. Thank you for your help.

**Comment by DanielChappuis** [comment]
You are welcome.
