### ISSUE TITLE
Rigidbody rotation constraints?

### ISSUE THREAD

**Issue by georgelam6** [DanielChappuis/reactphysics3d#175]
Does this physics engine allow constraining the rotation on one or more axes, like Bullet Physics or PhysX? If not, how would I go about implementing it myself?

**Comment by DanielChappuis** [comment]
Hello. Thanks for your request.

This feature has already been requested several times as you can see [here](https://github.com/DanielChappuis/reactphysics3d/issues/33) for instance.

I plan to implement this in the next release of the library. 
I am not sure yet when this will be released exactly but I will let you know here.
