### ISSUE TITLE
Unstable Rotation

### ISSUE THREAD

**Issue by georgelam6** [DanielChappuis/reactphysics3d#177]
![ezgif-6-543c504de3d9](https://user-images.githubusercontent.com/29050483/99888188-f1e98500-2c9e-11eb-9495-1b76a7d7afab.gif)

I am experiencing a strange issue with rotation, as you can see in the gif above.

Here is how I am getting the rotation euler in degrees, to apply to `glm::rotate` to get the model matrix:
```cpp
glm::vec3 Rigidbody::GetRotation() {
	glm::quat q(
		m_body->getTransform().getOrientation().x,
		m_body->getTransform().getOrientation().y,
		m_body->getTransform().getOrientation().z,
		m_body->getTransform().getOrientation().w);

	glm::vec3 result = glm::degrees(glm::eulerAngles(q));

	return glm::vec3(result.y, result.z, result.x);
}
```
Am I doing something wrong, or is this a bug?

**Comment by georgelam6** [comment]
Looks like I was doing something wrong. Doing this instead fixed it:
```cpp
glm::vec3 Rigidbody::GetRotation() {
	glm::quat q(
		m_body->getTransform().getOrientation().y,
		m_body->getTransform().getOrientation().z,
		m_body->getTransform().getOrientation().x,
		m_body->getTransform().getOrientation().w);

	glm::vec3 result = glm::degrees(glm::eulerAngles(q));

	return glm::vec3(result.x, result.y, result.z);
}
```
I think it's due to the fact that ReactPhysics3D's quaternions don't use the same order as GLM's (GLM's quaternions are a bit strange), so the conversion matters a lot.

**Comment by DanielChappuis** [comment]
Perfect. Glad that you have found your issue.
