### ISSUE TITLE
Is there some way to have a body act only like a sensor?

### ISSUE THREAD

**Issue by cpusam** [DanielChappuis/reactphysics3d#178]
Hi, so, is possible that? I've searched the examples and the doc for something to set the body like sensor (not process collision).
I know about the normal detection of touch with traditional functions, but with body, I suppose to evitate over processing, cause the engine use something like spatial BVH.
May you give me some exaple with body like sensor?

**Comment by DanielChappuis** [comment]
Can you please describe exactly what do you mean by "sensor" ? What are you trying to do exactly ?

I am not sure but maybe you want to use a "Trigger". A trigger is a collider that cannot collide with any other colliders but can only report when it's overlapping with another collider. You can find more information about a Trigger in ReactPhysics3d [here](https://reactphysics3d.com/usermanual.html#x1-5500011.4).

**Comment by cpusam** [comment]
@DanielChappuis so, it's exactly this I need! Thanks for the answer. Next time I will read all the docs.

**Comment by DanielChappuis** [comment]
No problem. Glad that I could help.
