### ISSUE TITLE
Is FixedJoint CANUSE?

### ISSUE THREAD

**Issue by LLRukia** [DanielChappuis/reactphysics3d#179]
I created a fixedjoint in my test program, and I give a speed (no matter linear or angular) to one of the rigid body of joint.
I can see it rotate totally irregular.

Then I review the code of SolveFixedJointSystem, I found a clerical error at line 457:
`Vector3 w1 = mFixedJointComponents.mI2[i] * angularImpulseBody1;`

I fixed it and try again, it behaves the same as before.

I am confused that does FixedJoint work well?

**Comment by DanielChappuis** [comment]
Hello. Thanks for your feedback.

I am not sure I understand your scenario. Can you please describe precisely what is your scenario, what behavior do you expect and what is happening ? 

> Then I review the code of SolveFixedJointSystem, I found a clerical error at line 457:
> `Vector3 w1 = mFixedJointComponents.mI2[i] * angularImpulseBody1;`

Why do you think there is an error ? Can you please give some explanation ?

**Comment by LLRukia** [comment]
![1](https://user-images.githubusercontent.com/35130995/100034810-f5644400-2e37-11eb-8ecb-f777dfd20af1.gif)

when apply the impulse to rigid body 1, why using inertia tensor of body 2?
I understand that the impulse applied to each body is equal, and I think when changing angular speed should use inertia tensor of the body which is applying impulse.

I notice that the same position correction code in BallandSocketJoint, which use `mI2`:
`const Vector3 w2 = mBallAndSocketJointComponents.mI2[i] * angularImpulseBody2;`

If there are any mistake, plz advise me.

**Comment by LLRukia** [comment]
![ball_and_socket_joint_constraint_unlock](https://user-images.githubusercontent.com/35130995/100035923-26457880-2e3a-11eb-96c5-b7d0e567f54e.gif)
I expect this behavior. This is a custom ball and socket joint rotation constraint. I think when the limit is violated, it behaves like a fixed joint.

**Comment by DanielChappuis** [comment]
Ok I see. Yes it's seems to be an error.

I have fixed this issue in the "issue_179" branch [here](https://github.com/DanielChappuis/reactphysics3d/tree/issue_179). Could you try to pull this branch and see if it fixes the issue on your side ?

**Comment by LLRukia** [comment]
I found another error at `FixedJointComponents.cpp`, in function `moveComponentToIndex`:
`new (mImpulseTranslation + destIndex) Vector3(mImpulseRotation[srcIndex]);`
It should be `new (mImpulseTranslation + destIndex) Vector3(mImpulseTranslation [srcIndex]);`

**Comment by LLRukia** [comment]
And it seems to work well after we fix these 2 errors!

**Comment by DanielChappuis** [comment]
Perfect. I have pushed both fixes on the master branch. 

Thanks a lot for your contribution.
