### ISSUE TITLE
Get current hinge joint angle

### ISSUE THREAD

**Issue by Omroth** [DanielChappuis/reactphysics3d#180]
In the previous version I defined a function to get the current hinge joint angle:

decimal HingeJoint::getHingeAngle()
{
    // Get the bodies positions and orientations
    const Vector3& x1 = mBody1->mCenterOfMassWorld;
    const Vector3& x2 = mBody2->mCenterOfMassWorld;
    const Quaternion& orientationBody1 = mBody1->getTransform().getOrientation();
    const Quaternion& orientationBody2 = mBody2->getTransform().getOrientation();

    // Compute the current angle around the hinge axis
    decimal hingeAngle = computeCurrentHingeAngle(orientationBody1, orientationBody2);

    return hingeAngle;
}

It does not appear to be as simple in the new version - could you advise please?

Thanks,
Ian

**Comment by DanielChappuis** [comment]
Good idea. I have added the method HingeJoint::getAngle() for that in the [master](https://github.com/DanielChappuis/reactphysics3d/commits/master) branch with this [commit](https://github.com/DanielChappuis/reactphysics3d/commit/23abaa905dff0dfb0672ac2e7c2e472135e44bab).

Let me know if this is OK for you.

**Comment by Omroth** [comment]
Thank you so much Daniel

**Comment by DanielChappuis** [comment]
You are welcome. I am closing this issue.
Do not hesitate to reopen it if something is not working as expected.
