### ISSUE TITLE
Crash in std::mutex::lock

### ISSUE THREAD

**Issue by Omroth** [DanielChappuis/reactphysics3d#181]
![image](https://user-images.githubusercontent.com/48519294/100517824-8a8f7180-3185-11eb-99d2-3387e84d0448.png)

I'm getting this crash when calling createPhysicsWorld after moving to the new version - all worked previously.  Any way you can work out what the problem is?

**Comment by DanielChappuis** [comment]
Can you post a very simple code that is crashing (where you create the PhysicsCommon object and you call the PhysicsCommon::createPhysicsWorld object) ?

**Comment by Omroth** [comment]
rp3d::PhysicsWorld::WorldSettings settings; 
	settings.defaultVelocitySolverNbIterations = 20; 
	settings.isSleepingEnabled = false; 
	settings.gravity = rp3d::Vector3(0, 0, -9.81); 


	dworld = physics_common->createPhysicsWorld(settings);

**Comment by DanielChappuis** [comment]
Thanks but can you try to create a very simple C++ project where you use this code to create a PhysicsWorld ? Does this very simple project crash or not ?

**Comment by Omroth** [comment]
I've made it work by having physics_common be a global variable.

How would you suggest physics_common be used in a large project?

**Comment by DanielChappuis** [comment]
I am glad that you have found the issue.

> How would you suggest physics_common be used in a large project?

You just need to make sure that the PhysicsCommon object persists and is not destroyed until the end of your application. For instance, you can allocate it dynamically:

```
// Allocate the PhysicsCommon object at the beginning
rp3d::PhysicsCommon* physicsCommon = new rp3d::PhysicsCommon();

...

// Delete it only at the end when you application exists for instance
delete physicsCommon;
```

Can I close this issue ?
