### ISSUE TITLE
Exit from 'setlocal'. Error on install library

### ISSUE THREAD

**Issue by snaulX** [DanielChappuis/reactphysics3d#182]
I build the reactphysics3d project on Release. Next I build the INSTALL project on Release and it cause this error: Серьезность		MSB3073	exit from command "setlocal
"C:\Program Files\CMake\bin\cmake.exe" -DBUILD_TYPE=Release -P cmake_install.cmake
if %errorlevel% neq 0 goto :cmEnd
:cmEnd
endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
:cmErrorLevel
exit /b %1
:cmDone
if %errorlevel% neq 0 goto :VCEnd
:VCEnd" with code 1.	INSTALL	D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets	153	
How to fix this? Im using Visual Studio 2019 on Windows 10.

**Comment by DanielChappuis** [comment]
This error doesn't seem to be related to the ReactPhysics3D library. Maybe you could search Google for help. For instance, I have found this [post](https://social.msdn.microsoft.com/Forums/en-US/02d24b1e-65ff-4177-bdf2-0d1e0fb8cdf6/error-msb3073-and-my-build-exited-with-code-1?forum=vcgeneral).

**Comment by snaulX** [comment]
It's weird that this site didn't appear when I googled, but the solution worked. Thank you
