### ISSUE TITLE
Assertion failed on exit when using the first documentation example

### ISSUE THREAD

**Issue by Zylann** [DanielChappuis/reactphysics3d#185]
Windows 10 64 bits, debug build, 0.8.0

I'm getting started with the first example found in the doc: https://github.com/DanielChappuis/reactphysics3d/blob/master/helloworld/Main.cpp

Which I isolated in my project as such:
```cpp
void doc_test() {
	using namespace rp3d;

	// First you need to create the PhysicsCommon object.
	// This is a factory module that you can use to create physics
	// world and other objects. It is also responsible for
	// logging and memory management
	PhysicsCommon physicsCommon;

	// Create a physics world
	PhysicsWorld *world = physicsCommon.createPhysicsWorld();

	// Create a rigid body in the world
	Vector3 position(0, 20, 0);
	Quaternion orientation = Quaternion::identity();
	Transform transform(position, orientation);
	RigidBody *body = world->createRigidBody(transform);

	const decimal timeStep = 1.0f / 60.0f;

	// Step the simulation a few steps
	for (int i = 0; i < 20; i++) {

		world->update(timeStep);

		// Get the updated position of the body
		const Transform &transform = body->getTransform();
		const Vector3 &position = transform.getPosition();

		// Display the position of the body
		std::cout << "Body Position: (" << position.x << ", " << position.y << ", " << position.z << ")" << std::endl;
	}
}
```

It runs fine and outputs a slowly falling position, but then on exiting the function in reaches an assertion failure in `PhysicsWorld.cpp`:
```cpp
    assert(mCollisionBodyComponents.getNbComponents() == 0);
```

![image](https://user-images.githubusercontent.com/1311555/106656296-6b043300-6592-11eb-8b86-23fedb7bab1b.png)

Is there something missing from the example?

This does not happen if I add this to the end of the function, despite the doc saying it would cleanup objects automatically:
```cpp
	world->destroyRigidBody(body);
```

---------

I got the version I'm using from the website.
But it might be that you fixed the issue here: https://github.com/DanielChappuis/reactphysics3d/commit/a855a81d04393f0c3c42331b54039fecbe1e7f89
Haven't tested yet

**Comment by DanielChappuis** [comment]
Hello. I have just tested your code with the master branch and it's seems to be working (on Linux).
As you said, this has probably been fixed in the master branch.

Note that the master branch is the last released version plus some hot fixes. The website only has the last released version.

Could you try again with the master branch and let me know if it's working on your side ?

**Comment by Zylann** [comment]
Getting the master version fixed it. Thanks!

**Comment by DanielChappuis** [comment]
Perfect thanks for the feedback.
