### ISSUE TITLE
HeightField declares initBVHTree() but doesnt seem to implement it

### ISSUE THREAD

**Issue by Zylann** [DanielChappuis/reactphysics3d#188]
`HeightFieldShape` declares `initBVHTree()` here:
https://github.com/DanielChappuis/reactphysics3d/blob/23abaa905dff0dfb0672ac2e7c2e472135e44bab/include/reactphysics3d/collision/shapes/HeightFieldShape.h#L109

But I cannot see any implementation of it in https://github.com/DanielChappuis/reactphysics3d/blob/master/src/collision/shapes/HeightFieldShape.cpp
Is it an oversight?

**Comment by DanielChappuis** [comment]
Hello. 

Yes this method declaration is not used anymore (probably from some old code). I have just removed it in this [commit](https://github.com/DanielChappuis/reactphysics3d/commit/4d14c8e8549784166edc46fd96884fd69d16b928) in the "develop" branch.

Thanks a lot for reporting this.
