### ISSUE TITLE
I'm not sure if this is a glitch, or me being dumb, but I cannot figure this out and I have spent forever on this.

### ISSUE THREAD

**Issue by Rorybabory** [DanielChappuis/reactphysics3d#189]
[createCollider.txt](https://github.com/DanielChappuis/reactphysics3d/files/5915327/createCollider.txt)

This is the code to try to create a 6 sided floor convex mesh. I am using it as a floor mesh, and what always happens is an object bounces off of it once, then passes right through it. The reason I have to use a convex hull instead of a box collider is because I need to use the model output from my level editor, and that outputs mesh data. The only difference I can see between my code and the manual is that in the manual they are using a shape made of quads, and my mesh is made of triangles.

**Comment by DanielChappuis** [comment]
Did you make sure that your triangles are correctly oriented ? The vertices of each triangle must be oriented counter-clockwise as seen from the outside of your mesh.

Note that it is better to use quads faces instead of triangular faces in order to avoid coplanar faces that could create ghost collisions.

**Comment by Rorybabory** [comment]
Hi, thanks for the reply!
I tried both of those suggestions and it still didn't work out, only this time the object just falls through instead of bouncing once. I also tried with the vertex list and index list in the manual, and it still didn't work so I think that part of the code can be ruled out.
Again, thanks for the response!

**Comment by DanielChappuis** [comment]
I have tested your code. First, all your triangle faces are oriented clockwise as seen from the outside of the mesh. As I said in my first post, they need to be oriented counter-clockwise.

Secondly, the two arrays for your vertices and indices need to be stored in a persistent way and available during the whole simulation. In you code, you only use them at the beginning to create the shape and destroy them before the simulation. Those two arrays need to be available during the simulation and destroyed only at the end.

Therefore, if you replace your array initialization with the following code, it should be better:

```
float* vertexArray = new float[24] {
        -5, -3, -5,
        -5, 3, -5,
        -5, -3, 5,
        -5, 3, 5,
        5, -3, -5,
        5, 3, -5,
        5, -3, 5,
        5, 3, 5
};
int* indicesArray = new int[36] {
        2,7,3,
        7,2,6,
        6,5,7,
        5,6,4,
        4,1,5,
        1,4,0,
        0,3,1,
        3,0,2,
        3,5,1,
        5,3,7,
        0,6,2,
        6,0,4,
};
```
  

Note that the arrays are now allocated using the "new" operator to make them persistent and also that the faces are now oriented counter-clockwise as seen from the outside of the mesh.

I hope this helps.

**Comment by Rorybabory** [comment]
Wow that worked! Thanks so much! I have spent over two months trying to get convex hulls working, including jumping from physics engine to physics engine. Again, thanks so much for the help with this!

**Comment by Rorybabory** [comment]
So wait I thought I thought I your solution had fixed the issue, but there was one thing I didn't test. I added to that code a wall with the same indices but with different vertices (vertices listed below) and it didn't work. The player could stand on top of the wall, just like how the player could stand on the floor, but the player does not collide with side of the wall object. The player is defined as a capsule collider, that is moving with setLinearVelocity.


the vertex positions are:
-12 5 -12
-12 17 -12
-12 5 12
-12 17 12
-10 5 -12
-10 17 -12
-10 5 12
-10 17 12

And the indices are the same as the ones you gave.

**Comment by DanielChappuis** [comment]
Could you please post a full part of your code that I could directly try one my side ?

Also note what I have commented before:

> Note that it is better to use quads faces instead of triangular faces in order to avoid coplanar faces that could create ghost collisions.

Not sure but maybe you are observing artifacts that are related to this.

**Comment by Rorybabory** [comment]
Sorry its taken so long for me to get back to you. I just tried using quads instead of tris, and it completely fixed all my problems! Thanks so much!
