### ISSUE TITLE
Any Problems with duplicate vertices in creating Convex Mesh

### ISSUE THREAD

**Issue by intelatrix** [DanielChappuis/reactphysics3d#194]
I'm trying to create a convex mesh now. 
Does having duplicate vertices affects the building of convex meshes in any way?

**Comment by DanielChappuis** [comment]
Yes, it is currently not supported in the library to create a convex mesh shape that contains duplicated vertices.

When a ConvexMeshShape is created, each vertex needs to be part of at least three polygon faces.

This has been discussed in this [issue](https://github.com/DanielChappuis/reactphysics3d/issues/169).

The documentation has already been changed but the online documentation doesn't contain this change for the moment. Sorry for that.

**Comment by DanielChappuis** [comment]
I am closing this. Don't hesitate to open it again if you still have a question.
