### ISSUE TITLE
bug in RigidBodyComponents::allocate 

### ISSUE THREAD

**Issue by graphitemaster** [DanielChappuis/reactphysics3d#195]
Spent awhile tracking this one down, but the component allocation code only copies `sizeof(bool) * mNbComponents` instead of `sizeof(decimal)` for `mSleepTimes`

<https://github.com/DanielChappuis/reactphysics3d/blob/master/src/components/RigidBodyComponents.cpp#L101>

`memcpy(newSleepTimes, mSleepTimes, mNbComponents * sizeof(bool));`

**Comment by DanielChappuis** [comment]
I have pushed a [fix](https://github.com/DanielChappuis/reactphysics3d/commit/e5d9090441f71e4bb4cde24cb005b8efa25bdca3) for this bug in the master branch.

Thanks a lot for taking the time to investigate this issue. This is very helpful.
