### ISSUE TITLE
Help on applying local forces

### ISSUE THREAD

**Issue by andymel123** [DanielChappuis/reactphysics3d#202]
Hi,

I'm trying to build a space racer. The ship is a rigidBody and I try to set a local force (for example) at the position of the main engine when space is pressed.
I first thought, that I have to set the direction of the force in the local coordinate system of the object. For example 
position = (0, 0, -shipLength/2) and direction (0, 0, -force).
But this just led to spinning of the ship. I then tried to multiply the direction by the ships orientation quaternion. This works better (so it seems like the direction vector is meant to be in world coordinates). But it's still not flying on a straight line. 

Some code: 

When the ship is initialized...
```
_ship.addThruster(
    ThrusterEnum::main,                // main engine
    vec3(0, 0, SHIP_BODY_LENGTH / 2),  // pos of thruster
    vec3(0, 0, 1),                     // direction of thruster
    100000                             // thrust
);
```

And in the update method of the ship...
```
for (uint i = 0; i < (uint)ThrusterEnum::NUM; ++i) {
    const auto& thruster = thrusters[i];
    const rpQuat rpQuat = body->getTransform().getOrientation();
    const rpVec3 localForce = toRp3d(thruster.getCurrentForce());   // direction of the thruster, magnitude depending on user input
    const rpVec3 forceDirectionInWorldCoordinates = rpQuat * localForce;
    const rpVec3 rpPos = toRp3d(thruster.getPosition());
    
    if (localForce.length() > 0) {
        body->applyForceAtLocalPosition(
	    forceDirectionInWorldCoordinates,
	    rpPos
        );
    }
}
```
Any idea what I do wrong? What else can I add here? 
Thanks for any tip!!
And thanks for the nice library!!

**Comment by DanielChappuis** [comment]
Hello,

There are three different methods to apply a force to a body.

`RigidBody::applyForceAtLocalPosition(const Vector3& force, const Vector3& point)`

Here the force needs to be in world-space coordinates (I need to add this in the documentation), but the point where to apply the force needs to be in local-space coordinates.

`RigidBody::applyForceAtWorldPosition(const Vector3& force, const Vector3& point)`

Here the force needs to be in world-space coordinates, and the point where to apply the force needs to be in world-space coordinates too.

`RigidBody::applyForceToCenterOfMass(const Vector3& force)`

Here the force needs to be in world-space coordinates and the force is applied to the center of mass of the body.

Concerning the rotation of the body when you apply a force. Note that if you apply a force to a body at a location that is different from the center of mass, some torque is created and the body will start rotating. If you do not want the body to start rotating, you need to apply your force to the center of mass for instance by using the RigidBody::applyForceToCenterOfMass() method above.

I hope this helps.

**Comment by andymel123** [comment]
So it seems like my understanding is roughly correct so far, thanks a lot for helping me verifying this!

The problem is, I guess there should be no rotation with the current values (only z direction), as the center of mass and the thruster should be on a line parallel to the direction of the force. (The documentation states, that the center of mass is in the local origin on default):
```
local pos => (0, 0, SHIP_BODY_LENGTH / 2)
local direction => (0, 0, 1)
```
And then when applying the local force:
```
const rpQuat rpQuat = body->getTransform().getOrientation();
const rpVec3 forceDirectionInWorldCoordinates = rpQuat * localForce;

body->applyForceAtLocalPosition(
  forceDirectionInWorldCoordinates,
  rpPos
);
```

Do you have a best guess with your experience? Maybe rounding errors?!

**Comment by DanielChappuis** [comment]
As long as you do not call `RigidBody::updateMassPropertiesFromColliders()` or `RigidBody::setLocalCenterOfMass()` methods the center of mass of your body is at (0, 0, 0) in local-space. You can use the `RigidBody::getLocalCenterOfMass()` to make sure of this. In this case, if your local force is aligned with the z-axis, there should be no torque when applying your force at (0, 0, length/2) in local-space.

As you said maybe, rounding errors during the computation of the world-space force make the force not perfectly aligned with the z-axis. 

Could you try to use the `RigidBody::applyForceToCenterOfMass()` instead? If you do not want any torque, you should call this method. Let me know if this works.

**Comment by DanielChappuis** [comment]
Do you have any news about this? Can I close this issue?
