### ISSUE TITLE
Why does scaling matrices in openglframework use half-extent / radius?

### ISSUE THREAD

**Issue by goksanisil23** [DanielChappuis/reactphysics3d#207]
Hi,

I'm not exactly following the intuition behind using half-extent and radius for scaling the primitive shapes like box and sphere, in the openglframework (I understand the usage of half-extent in the physics system itself). 
Assuming the primitive shapes have normalized dimensions of (1,1,1) on each axis, why not just multiple by the length of each side ? 

Thanks

**Comment by DanielChappuis** [comment]
For instance for the box, yes, that's right, if the normalized length is 1, we would need to use the length to scale the shape.
However, if it is the normalized half-length that is 1, then we need to use the half-length to scale the shape. If you open the testbed/meshes/cube.obj file, you can see that this is indeed the case. The half-length of the cube is 1 (and its length is 2).

Both solutions are valid, it's just a matter of choice.

**Comment by goksanisil23** [comment]
Thank you very much for pointing out this out. I have missed the fact that asset files are exported in model space, which are centered around the origin, therefore the vertex coordinates are based on the half-extent.
