### ISSUE TITLE
Height field Collider and Debug renderer artifacts 

### ISSUE THREAD

**Issue by BryceStandley** [DanielChappuis/reactphysics3d#208]
I've been trying to implement the React library into my engine for a Uni project for a few days now and have run into a few issues mostly with generating the heightfield collider for out terrain.

On init of the application, our terrain is built from a heightmap file and stored for rendering, we also after the map is created, generate the collider for the terrain by getting the height values of our mesh. This works without any issues and is a very fast process but for some reason with we turn on the debugging renderer (implemented the same as the testbed application), we find there are some strange artifacts in the collider. 

I've confirmed the contents of the heightfield array is correct and there's  no corrupt or un-initialized data inside the array

Heres how we generate the heightfield array, Currently we are capping the height between 0 and 1 for testing but this will normally range from 0 to 100 or however much the height map heights land on.

`int nbRows = gameTerrain->getSize();
	int nbColumns = nbRows;
	float minHeight = 0;
	float maxHeight = 0;
	float heightCutoffMax = 1.0f;
	float heightCutooffMin = 0.0f;

	int size = nbRows * nbColumns;
	float heightValues[size];
	std::vector<float> terrainHeights = gameTerrain->GetTerrainHeights();

	for(int z = 0; z < nbRows; ++z)
	{
		for(int x = 0; x < nbColumns; ++x)
		{
			int index = z * nbRows + x;
			float temp = terrainHeights[index];

			if(temp > heightCutoffMax) {temp = heightCutoffMax;}
			if(temp < heightCutooffMin) { temp = heightCutooffMin;}

			heightValues[index] = temp;
			if(x == 0 && z == 0)
			{
				minHeight = heightValues[index];
				maxHeight = heightValues[index];
			}

			if(heightValues[index] < minHeight){minHeight = heightValues[index];}
			if(heightValues[index] > maxHeight){maxHeight = heightValues[index];}
		}
	}

	glm::vec3 s = gameTerrain->GetScales();
	rp3d::HeightFieldShape* col = physicsCommon.createHeightFieldShape(nbRows, nbColumns, minHeight, maxHeight, heightValues, rp3d::HeightFieldShape::HeightDataType::HEIGHT_FLOAT_TYPE);
	rp3d::Vector3 scales(gameTerrain->GetScales().x, gameTerrain->GetScales().y, gameTerrain->GetScales().z);
	//rp3d::Vector3 scales(2,2,2);
	col->setScale(scales);

	rp3d::Transform transform = rp3d::Transform::identity();
	rp3d::RigidBody* rb = physicsWorld->createRigidBody(transform);
	gameTerrain->terrainCollider = rb->addCollider(col, rp3d::Transform::identity());
	rb->updateMassPropertiesFromColliders();
	gameTerrain->terrainRigidbody = rb;
	gameTerrain->terrainRigidbody->setType(rp3d::BodyType::STATIC);`

This is the result with the debug renderer

![Screen Shot 2021-06-25 at 3 29 32 pm](https://user-images.githubusercontent.com/26952515/123387265-2bce9100-d5ca-11eb-8dab-81bd8793babc.png)

As expected the framerate dies as soon as the debugger is turned on for the collisions but that's mentioned in the documentation.  Its hard to tell if the collider and collisions are working correctly but currently, our event listener is triggering when the camera/player is over the collider so i believe collisions are working. Maybe not correctly but they are being triggered.

**Comment by DanielChappuis** [comment]
Hello. Thanks for reporting this.

Are you able to reproduce this with a small terrain? Small enough so that you can post the height field values of your terrain. This way I can try to reproduce the issue on my side.

**Comment by BryceStandley** [comment]
Hey Daniel, sorry for the late reply, these are the height values from a 16x16 terrain map.
`INPUT_LUA::FILE_FOUND::INPUT_SET
GLFW-WINDOW::INFO::GLFW Started!
SKYBOX_LUA::FILE_LOADED
Index: 0  ---  Value: 1
Index: 1  ---  Value: 1
Index: 2  ---  Value: 1
Index: 3  ---  Value: 1
Index: 4  ---  Value: 1
Index: 5  ---  Value: 1
Index: 6  ---  Value: 1
Index: 7  ---  Value: 1
Index: 8  ---  Value: 1
Index: 9  ---  Value: 1
Index: 10  ---  Value: 1
Index: 11  ---  Value: 1
Index: 12  ---  Value: 1
Index: 13  ---  Value: 1
Index: 14  ---  Value: 1
Index: 15  ---  Value: 1
Index: 16  ---  Value: 1
Index: 17  ---  Value: 1
Index: 18  ---  Value: 1
Index: 19  ---  Value: 1
Index: 20  ---  Value: 1
Index: 21  ---  Value: 1
Index: 22  ---  Value: 1
Index: 23  ---  Value: 1
Index: 24  ---  Value: 1
Index: 25  ---  Value: 1
Index: 26  ---  Value: 1
Index: 27  ---  Value: 1
Index: 28  ---  Value: 1
Index: 29  ---  Value: 1
Index: 30  ---  Value: 1
Index: 31  ---  Value: 1
Index: 32  ---  Value: 1
Index: 33  ---  Value: 1
Index: 34  ---  Value: 1
Index: 35  ---  Value: 1
Index: 36  ---  Value: 1
Index: 37  ---  Value: 1
Index: 38  ---  Value: 1
Index: 39  ---  Value: 1
Index: 40  ---  Value: 1
Index: 41  ---  Value: 1
Index: 42  ---  Value: 1
Index: 43  ---  Value: 1
Index: 44  ---  Value: 1
Index: 45  ---  Value: 1
Index: 46  ---  Value: 1
Index: 47  ---  Value: 1
Index: 48  ---  Value: 1
Index: 49  ---  Value: 1
Index: 50  ---  Value: 1
Index: 51  ---  Value: 1
Index: 52  ---  Value: 1
Index: 53  ---  Value: 1
Index: 54  ---  Value: 1
Index: 55  ---  Value: 1
Index: 56  ---  Value: 1
Index: 57  ---  Value: 1
Index: 58  ---  Value: 1
Index: 59  ---  Value: 1
Index: 60  ---  Value: 1
Index: 61  ---  Value: 1
Index: 62  ---  Value: 1
Index: 63  ---  Value: 1
Index: 64  ---  Value: 1
Index: 65  ---  Value: 1
Index: 66  ---  Value: 1
Index: 67  ---  Value: 1
Index: 68  ---  Value: 1
Index: 69  ---  Value: 1
Index: 70  ---  Value: 1
Index: 71  ---  Value: 1
Index: 72  ---  Value: 1
Index: 73  ---  Value: 1
Index: 74  ---  Value: 1
Index: 75  ---  Value: 1
Index: 76  ---  Value: 1
Index: 77  ---  Value: 1
Index: 78  ---  Value: 1
Index: 79  ---  Value: 1
Index: 80  ---  Value: 1
Index: 81  ---  Value: 1
Index: 82  ---  Value: 1
Index: 83  ---  Value: 1
Index: 84  ---  Value: 1
Index: 85  ---  Value: 1
Index: 86  ---  Value: 1
Index: 87  ---  Value: 1
Index: 88  ---  Value: 1
Index: 89  ---  Value: 1
Index: 90  ---  Value: 1
Index: 91  ---  Value: 1
Index: 92  ---  Value: 1
Index: 93  ---  Value: 1
Index: 94  ---  Value: 1
Index: 95  ---  Value: 1
Index: 96  ---  Value: 1
Index: 97  ---  Value: 1
Index: 98  ---  Value: 1
Index: 99  ---  Value: 1
Index: 100  ---  Value: 1
Index: 101  ---  Value: 1
Index: 102  ---  Value: 1
Index: 103  ---  Value: 1
Index: 104  ---  Value: 1
Index: 105  ---  Value: 1
Index: 106  ---  Value: 1
Index: 107  ---  Value: 1
Index: 108  ---  Value: 1
Index: 109  ---  Value: 1
Index: 110  ---  Value: 1
Index: 111  ---  Value: 1
Index: 112  ---  Value: 1
Index: 113  ---  Value: 1
Index: 114  ---  Value: 1
Index: 115  ---  Value: 1
Index: 116  ---  Value: 1
Index: 117  ---  Value: 1
Index: 118  ---  Value: 1
Index: 119  ---  Value: 1
Index: 120  ---  Value: 1
Index: 121  ---  Value: 1
Index: 122  ---  Value: 1
Index: 123  ---  Value: 1
Index: 124  ---  Value: 1
Index: 125  ---  Value: 1
Index: 126  ---  Value: 1
Index: 127  ---  Value: 1
Index: 128  ---  Value: 1
Index: 129  ---  Value: 1
Index: 130  ---  Value: 1
Index: 131  ---  Value: 1
Index: 132  ---  Value: 1
Index: 133  ---  Value: 1
Index: 134  ---  Value: 1
Index: 135  ---  Value: 1
Index: 136  ---  Value: 1
Index: 137  ---  Value: 1
Index: 138  ---  Value: 1
Index: 139  ---  Value: 1
Index: 140  ---  Value: 1
Index: 141  ---  Value: 1
Index: 142  ---  Value: 1
Index: 143  ---  Value: 1
Index: 144  ---  Value: 1
Index: 145  ---  Value: 1
Index: 146  ---  Value: 1
Index: 147  ---  Value: 1
Index: 148  ---  Value: 1
Index: 149  ---  Value: 1
Index: 150  ---  Value: 1
Index: 151  ---  Value: 1
Index: 152  ---  Value: 1
Index: 153  ---  Value: 1
Index: 154  ---  Value: 1
Index: 155  ---  Value: 1
Index: 156  ---  Value: 1
Index: 157  ---  Value: 1
Index: 158  ---  Value: 1
Index: 159  ---  Value: 1
Index: 160  ---  Value: 1
Index: 161  ---  Value: 1
Index: 162  ---  Value: 1
Index: 163  ---  Value: 1
Index: 164  ---  Value: 1
Index: 165  ---  Value: 1
Index: 166  ---  Value: 1
Index: 167  ---  Value: 1
Index: 168  ---  Value: 1
Index: 169  ---  Value: 1
Index: 170  ---  Value: 1
Index: 171  ---  Value: 1
Index: 172  ---  Value: 1
Index: 173  ---  Value: 1
Index: 174  ---  Value: 1
Index: 175  ---  Value: 1
Index: 176  ---  Value: 1
Index: 177  ---  Value: 1
Index: 178  ---  Value: 1
Index: 179  ---  Value: 1
Index: 180  ---  Value: 1
Index: 181  ---  Value: 1
Index: 182  ---  Value: 1
Index: 183  ---  Value: 1
Index: 184  ---  Value: 1
Index: 185  ---  Value: 1
Index: 186  ---  Value: 1
Index: 187  ---  Value: 1
Index: 188  ---  Value: 1
Index: 189  ---  Value: 1
Index: 190  ---  Value: 1
Index: 191  ---  Value: 1
Index: 192  ---  Value: 1
Index: 193  ---  Value: 1
Index: 194  ---  Value: 1
Index: 195  ---  Value: 1
Index: 196  ---  Value: 1
Index: 197  ---  Value: 1
Index: 198  ---  Value: 1
Index: 199  ---  Value: 1
Index: 200  ---  Value: 1
Index: 201  ---  Value: 1
Index: 202  ---  Value: 1
Index: 203  ---  Value: 1
Index: 204  ---  Value: 1
Index: 205  ---  Value: 1
Index: 206  ---  Value: 1
Index: 207  ---  Value: 1
Index: 208  ---  Value: 1
Index: 209  ---  Value: 1
Index: 210  ---  Value: 1
Index: 211  ---  Value: 1
Index: 212  ---  Value: 1
Index: 213  ---  Value: 1
Index: 214  ---  Value: 1
Index: 215  ---  Value: 1
Index: 216  ---  Value: 1
Index: 217  ---  Value: 1
Index: 218  ---  Value: 1
Index: 219  ---  Value: 1
Index: 220  ---  Value: 1
Index: 221  ---  Value: 1
Index: 222  ---  Value: 1
Index: 223  ---  Value: 1
Index: 224  ---  Value: 1
Index: 225  ---  Value: 1
Index: 226  ---  Value: 1
Index: 227  ---  Value: 1
Index: 228  ---  Value: 1
Index: 229  ---  Value: 1
Index: 230  ---  Value: 1
Index: 231  ---  Value: 1
Index: 232  ---  Value: 1
Index: 233  ---  Value: 1
Index: 234  ---  Value: 1
Index: 235  ---  Value: 1
Index: 236  ---  Value: 1
Index: 237  ---  Value: 1
Index: 238  ---  Value: 1
Index: 239  ---  Value: 1
Index: 240  ---  Value: 1
Index: 241  ---  Value: 1
Index: 242  ---  Value: 1
Index: 243  ---  Value: 1
Index: 244  ---  Value: 1
Index: 245  ---  Value: 1
Index: 246  ---  Value: 1
Index: 247  ---  Value: 1
Index: 248  ---  Value: 1
Index: 249  ---  Value: 1
Index: 250  ---  Value: 1
Index: 251  ---  Value: 1
Index: 252  ---  Value: 1
Index: 253  ---  Value: 1
Index: 254  ---  Value: 1
Index: 255  ---  Value: 1
`

Heres the result in the debugger
![Screen Shot 2021-06-27 at 2 32 53 pm](https://user-images.githubusercontent.com/26952515/123535147-b5aa6580-d754-11eb-9038-c65bb8b5772e.png)


And this is the heightmap used
![noiseTexture(2)](https://user-images.githubusercontent.com/26952515/123535159-c35feb00-d754-11eb-908f-64a1d609058e.png)

**Comment by BryceStandley** [comment]
Sorry no idea why the console output looks like that in a code block.

`ENGINE::SCRIPT_RUNNING
INPUT_LUA::FILE_FOUND::INPUT_SET
GLFW-WINDOW::INFO::GLFW Started!
SKYBOX_LUA::FILE_LOADED
Index: 0  ---  Value: 1
Index: 1  ---  Value: 1
Index: 2  ---  Value: 1
Index: 3  ---  Value: 1
Index: 4  ---  Value: 1
Index: 5  ---  Value: 1
Index: 6  ---  Value: 1
Index: 7  ---  Value: 1
Index: 8  ---  Value: 1
Index: 9  ---  Value: 1
Index: 10  ---  Value: 1
Index: 11  ---  Value: 1
Index: 12  ---  Value: 1
Index: 13  ---  Value: 1
Index: 14  ---  Value: 1
Index: 15  ---  Value: 1
Index: 16  ---  Value: 1
Index: 17  ---  Value: 1
Index: 18  ---  Value: 1
Index: 19  ---  Value: 1
Index: 20  ---  Value: 1
Index: 21  ---  Value: 1
Index: 22  ---  Value: 1
Index: 23  ---  Value: 1
Index: 24  ---  Value: 1
Index: 25  ---  Value: 1
Index: 26  ---  Value: 1
Index: 27  ---  Value: 1
Index: 28  ---  Value: 1
Index: 29  ---  Value: 1
Index: 30  ---  Value: 1
Index: 31  ---  Value: 1
Index: 32  ---  Value: 1
Index: 33  ---  Value: 1
Index: 34  ---  Value: 1
Index: 35  ---  Value: 1
Index: 36  ---  Value: 1
Index: 37  ---  Value: 1
Index: 38  ---  Value: 1
Index: 39  ---  Value: 1
Index: 40  ---  Value: 1
Index: 41  ---  Value: 1
Index: 42  ---  Value: 1
Index: 43  ---  Value: 1
Index: 44  ---  Value: 1
Index: 45  ---  Value: 1
Index: 46  ---  Value: 1
Index: 47  ---  Value: 1
Index: 48  ---  Value: 1
Index: 49  ---  Value: 1
Index: 50  ---  Value: 1
Index: 51  ---  Value: 1
Index: 52  ---  Value: 1
Index: 53  ---  Value: 1
Index: 54  ---  Value: 1
Index: 55  ---  Value: 1
Index: 56  ---  Value: 1
Index: 57  ---  Value: 1
Index: 58  ---  Value: 1
Index: 59  ---  Value: 1
Index: 60  ---  Value: 1
Index: 61  ---  Value: 1
Index: 62  ---  Value: 1
Index: 63  ---  Value: 1
Index: 64  ---  Value: 1
Index: 65  ---  Value: 1
Index: 66  ---  Value: 1
Index: 67  ---  Value: 1
Index: 68  ---  Value: 1
Index: 69  ---  Value: 1
Index: 70  ---  Value: 1
Index: 71  ---  Value: 1
Index: 72  ---  Value: 1
Index: 73  ---  Value: 1
Index: 74  ---  Value: 1
Index: 75  ---  Value: 1
Index: 76  ---  Value: 1
Index: 77  ---  Value: 1
Index: 78  ---  Value: 1
Index: 79  ---  Value: 1
Index: 80  ---  Value: 1
Index: 81  ---  Value: 1
Index: 82  ---  Value: 1
Index: 83  ---  Value: 1
Index: 84  ---  Value: 1
Index: 85  ---  Value: 1
Index: 86  ---  Value: 1
Index: 87  ---  Value: 1
Index: 88  ---  Value: 1
Index: 89  ---  Value: 1
Index: 90  ---  Value: 1
Index: 91  ---  Value: 1
Index: 92  ---  Value: 1
Index: 93  ---  Value: 1
Index: 94  ---  Value: 1
Index: 95  ---  Value: 1
Index: 96  ---  Value: 1
Index: 97  ---  Value: 1
Index: 98  ---  Value: 1
Index: 99  ---  Value: 1
Index: 100  ---  Value: 1
Index: 101  ---  Value: 1
Index: 102  ---  Value: 1
Index: 103  ---  Value: 1
Index: 104  ---  Value: 1
Index: 105  ---  Value: 1
Index: 106  ---  Value: 1
Index: 107  ---  Value: 1
Index: 108  ---  Value: 1
Index: 109  ---  Value: 1
Index: 110  ---  Value: 1
Index: 111  ---  Value: 1
Index: 112  ---  Value: 1
Index: 113  ---  Value: 1
Index: 114  ---  Value: 1
Index: 115  ---  Value: 1
Index: 116  ---  Value: 1
Index: 117  ---  Value: 1
Index: 118  ---  Value: 1
Index: 119  ---  Value: 1
Index: 120  ---  Value: 1
Index: 121  ---  Value: 1
Index: 122  ---  Value: 1
Index: 123  ---  Value: 1
Index: 124  ---  Value: 1
Index: 125  ---  Value: 1
Index: 126  ---  Value: 1
Index: 127  ---  Value: 1
Index: 128  ---  Value: 1
Index: 129  ---  Value: 1
Index: 130  ---  Value: 1
Index: 131  ---  Value: 1
Index: 132  ---  Value: 1
Index: 133  ---  Value: 1
Index: 134  ---  Value: 1
Index: 135  ---  Value: 1
Index: 136  ---  Value: 1
Index: 137  ---  Value: 1
Index: 138  ---  Value: 1
Index: 139  ---  Value: 1
Index: 140  ---  Value: 1
Index: 141  ---  Value: 1
Index: 142  ---  Value: 1
Index: 143  ---  Value: 1
Index: 144  ---  Value: 1
Index: 145  ---  Value: 1
Index: 146  ---  Value: 1
Index: 147  ---  Value: 1
Index: 148  ---  Value: 1
Index: 149  ---  Value: 1
Index: 150  ---  Value: 1
Index: 151  ---  Value: 1
Index: 152  ---  Value: 1
Index: 153  ---  Value: 1
Index: 154  ---  Value: 1
Index: 155  ---  Value: 1
Index: 156  ---  Value: 1
Index: 157  ---  Value: 1
Index: 158  ---  Value: 1
Index: 159  ---  Value: 1
Index: 160  ---  Value: 1
Index: 161  ---  Value: 1
Index: 162  ---  Value: 1
Index: 163  ---  Value: 1
Index: 164  ---  Value: 1
Index: 165  ---  Value: 1
Index: 166  ---  Value: 1
Index: 167  ---  Value: 1
Index: 168  ---  Value: 1
Index: 169  ---  Value: 1
Index: 170  ---  Value: 1
Index: 171  ---  Value: 1
Index: 172  ---  Value: 1
Index: 173  ---  Value: 1
Index: 174  ---  Value: 1
Index: 175  ---  Value: 1
Index: 176  ---  Value: 1
Index: 177  ---  Value: 1
Index: 178  ---  Value: 1
Index: 179  ---  Value: 1
Index: 180  ---  Value: 1
Index: 181  ---  Value: 1
Index: 182  ---  Value: 1
Index: 183  ---  Value: 1
Index: 184  ---  Value: 1
Index: 185  ---  Value: 1
Index: 186  ---  Value: 1
Index: 187  ---  Value: 1
Index: 188  ---  Value: 1
Index: 189  ---  Value: 1
Index: 190  ---  Value: 1
Index: 191  ---  Value: 1
Index: 192  ---  Value: 1
Index: 193  ---  Value: 1
Index: 194  ---  Value: 1
Index: 195  ---  Value: 1
Index: 196  ---  Value: 1
Index: 197  ---  Value: 1
Index: 198  ---  Value: 1
Index: 199  ---  Value: 1
Index: 200  ---  Value: 1
Index: 201  ---  Value: 1
Index: 202  ---  Value: 1
Index: 203  ---  Value: 1
Index: 204  ---  Value: 1
Index: 205  ---  Value: 1
Index: 206  ---  Value: 1
Index: 207  ---  Value: 1
Index: 208  ---  Value: 1
Index: 209  ---  Value: 1
Index: 210  ---  Value: 1
Index: 211  ---  Value: 1
Index: 212  ---  Value: 1
Index: 213  ---  Value: 1
Index: 214  ---  Value: 1
Index: 215  ---  Value: 1
Index: 216  ---  Value: 1
Index: 217  ---  Value: 1
Index: 218  ---  Value: 1
Index: 219  ---  Value: 1
Index: 220  ---  Value: 1
Index: 221  ---  Value: 1
Index: 222  ---  Value: 1
Index: 223  ---  Value: 1
Index: 224  ---  Value: 1
Index: 225  ---  Value: 1
Index: 226  ---  Value: 1
Index: 227  ---  Value: 1
Index: 228  ---  Value: 1
Index: 229  ---  Value: 1
Index: 230  ---  Value: 1
Index: 231  ---  Value: 1
Index: 232  ---  Value: 1
Index: 233  ---  Value: 1
Index: 234  ---  Value: 1
Index: 235  ---  Value: 1
Index: 236  ---  Value: 1
Index: 237  ---  Value: 1
Index: 238  ---  Value: 1
Index: 239  ---  Value: 1
Index: 240  ---  Value: 1
Index: 241  ---  Value: 1
Index: 242  ---  Value: 1
Index: 243  ---  Value: 1
Index: 244  ---  Value: 1
Index: 245  ---  Value: 1
Index: 246  ---  Value: 1
Index: 247  ---  Value: 1
Index: 248  ---  Value: 1
Index: 249  ---  Value: 1
Index: 250  ---  Value: 1
Index: 251  ---  Value: 1
Index: 252  ---  Value: 1
Index: 253  ---  Value: 1
Index: 254  ---  Value: 1
Index: 255  ---  Value: 1
WORLD::RUNNING
CLOSING::ENGINE_WILL_EXIT
Debugger.cpp::Log File written to: ./res/logs/tnah-engine.log

Process finished with exit code 0`

**Comment by BryceStandley** [comment]
I should note currently our function clamps the collider value to 1  for testing and as all values of the collider are 1 i should expect to see a flat plane as a collider, ive gone though the debugger and checked and cant see anything that would cause this strange error. currently using the lastest 0.8 build, built in CLion with cmake

**Comment by BryceStandley** [comment]
I managed to fix this issue. After some back and forth with some other students that managed to get everything working, i found berried in our code, part of the colliders height data was being lost hence the strange collider behavour. Ive since corrected the issue by creating and saving a seperate height map for the collider and making sure it exists during the lifetime of the application.

**Comment by DanielChappuis** [comment]
Great. I am glad you have found the issue.
