### ISSUE TITLE
What's the principle behind it? Is it going through all the objects or going through the nearby objects by octree?

### ISSUE THREAD

**Issue by ActivePeter** [DanielChappuis/reactphysics3d#209]
What's the principle behind it? 
Is it going through all the objects or going through the nearby objects by octree?

**Comment by DanielChappuis** [comment]
Hello. What's the principle behind what ? What's 'it' in you question ?

**Comment by ActivePeter** [comment]
> Hello. What's the principle behind what ? What's 'it' in you question ?

this lib, I mean when I call the update() or testCollision() , how this lib check the collision? My expression may be not so correct

**Comment by DanielChappuis** [comment]
Ok I see. It's definitely not going through all the objects. The collision detection is separated in two phases. First the broadphase uses a Dynamic AABB Tree to retrieve the pair of bodies that have their AABB approximation overlap. Then during the narrow-phase we really test for collision between the actual collision shapes.

**Comment by ActivePeter** [comment]
> Ok I see. It's definitely not going through all the objects. The collision detection is separated in two phases. First the broadphase uses a Dynamic AABB Tree to retrieve the pair of bodies that have their AABB approximation overlap. Then during the narrow-phase we really test for collision between the actual collision shapes.

Thank you for answering😁

**Comment by DanielChappuis** [comment]
You are welcome.
