### ISSUE TITLE
Integered with OSG or other 3d scene library

### ISSUE THREAD

**Issue by ZzeWang** [DanielChappuis/reactphysics3d#213]
Hi, thank for such awsome engine, and I wonder that if ReactPhysics3d can be integered with other 3d scene library, such as OGRE , OSG or VTK like. This will be huge useful for me, thanks again!

**Comment by DanielChappuis** [comment]
Hello,

ReactPhysics3D is a C++ physics library. It does not handle the graphics part and therefore, you can use it with any graphics engine of your choice.

**Comment by DanielChappuis** [comment]
I hope I have answered your question. Can I close this issue?

**Comment by DanielChappuis** [comment]
I am closing this issue. Feel free to reopen it if necessary.
