### ISSUE TITLE
Don't set warning levels by default

### ISSUE THREAD

**Issue by seanmiddleditch** [DanielChappuis/reactphysics3d#220]
https://github.com/DanielChappuis/reactphysics3d/blob/c1d6146291cca3d4af8724a4f15005ea8fcd8331/CMakeLists.txt#L259

Setting warning levels like those assumes that users are using the same compilers (and same versions thereof) as you are in your testing, and punishes users with spammy build logs if they're using newer compiler versions (which often come with new warnings!).

Ideally, warning levels for development purposes should instead be set in CI by setting the appropriate `CXXFLAGS` (probably along with `-Werror`) or locally by using appropriate tools like the new `CMakePresets.json` or equivalent.

**Comment by seanmiddleditch** [comment]
Thanks! You're a champ for jumping on all these. :)

**Comment by DanielChappuis** [comment]
The above fix is now part of the version [v0.9.0](https://github.com/DanielChappuis/reactphysics3d/releases/tag/v0.9.0) that has just been released.
