### ISSUE TITLE
HeightFieldShape::getVertexAt throws error

### ISSUE THREAD

**Issue by CallumCVM** [DanielChappuis/reactphysics3d#227]
As per the title, when setting up a HeightField with what I believe are sane values, line 312 of HeightFieldShape.cpp throws an assert because the vertex location calculated is not inside the AABB. I believe this to be incorrect because if I remove the assert and generate debug data, I can see the vertices are correctly aligned with my terrain (please see https://imgur.com/mFwTDf4).

I did note that during the AABB calculation in the constructor, the AABB is not subject to the same adjustment as on line 299:

`const decimal heightOrigin = -(mMaxHeight - mMinHeight) * decimal(0.5) - mMinHeight;` 

And this seems to cause the vertex being throw outside of the AABB. I did also note that during calculating my lowest and highest heightfield values, I had to subtract my terrain chunk's centre point in order for the terrain to align with react's heightfield. Or perhaps I am just setting it up entirely wrong?

**Comment by DanielChappuis** [comment]
Hello. Thanks a lot for taking the time to report this.

Can I ask you want are the coordinates of the AABB and the vertex coordinates at line 312 of HeightFieldShape.cpp when the assertion is thrown?



> I did note that during the AABB calculation in the constructor, the AABB is not subject to the same adjustment as on line 299:

Can I ask you what do you mean exactly?

**Comment by CallumCVM** [comment]
Sorry for the late reply @DanielChappuis, I ended up using PhysX instead and no longer have the relevent code to show you. Its probably worth nothing that with a physx height field using the exact same data, I did not experience the same issue, so I do believe its something with your solution causing the issue. Good luck :)

**Comment by DanielChappuis** [comment]
Ok. Thanks a lot for your feedback. Good luck with your project.
I am closing this issue for the moment.
