### ISSUE TITLE
Does this support iOS?

### ISSUE THREAD

**Issue by ccworld1000** [DanielChappuis/reactphysics3d#229]
Does this support iOS?

**Comment by DanielChappuis** [comment]
It is officialy supported on Linux, Windows and MacOS with a C++11 compiler.
I have never tried to compile it for iOS however.

**Comment by mokalux** [comment]
I can confirm it works for android, it should be working for ios too (giderosmobile uses this library and I haven't heard of any problem using it for ios, I use it for android though).

**Comment by DanielChappuis** [comment]
@mokalux Thanks for your addition

**Comment by ccworld1000** [comment]
It seems a little complicated. GL has been abandoned. I may need to find a graphical API that is active in consulting the system association.

**Comment by DanielChappuis** [comment]
Yes you will probably need to use Metal API on iOS. Note that the ReactPhysics3D library does not depends on OpenGL (or any graphical API). You can use it with anything you want.

**Comment by DanielChappuis** [comment]
I am closing this issue. Do not hesitate to reopen it if necessary.
