### ISSUE TITLE
[Feature request] concave meshes

### ISSUE THREAD

**Issue by ColinGilbert** [DanielChappuis/reactphysics3d#23]
Hi,

I have been using rp3d for a while, and a big thing that makes life difficult is having to run V-HACD upon my meshes in order to bring them into convex shapes. It takes forever and the result isn't completely accurate. Concave meshes would be really neat, especially for things such as terrain.

Thanks
Colin

**Comment by DanielChappuis** [comment]
Good news !
I am currently working on concave triangular meshes and terrain support (for static bodies only). This will be the major new features of the next release of the library.

**Comment by DanielChappuis** [comment]
The version 0.6.0 of ReactPhysics3D has been released and now supports collision shapes for static concave triangular mesh and height field.
