### ISSUE TITLE
RigidBody collision bug?

### ISSUE THREAD

**Issue by MatheusZickuhr** [DanielChappuis/reactphysics3d#235]
I have two rigid bodies on a scene, a box (dynamic type) and a floor (static type).

![image](https://user-images.githubusercontent.com/37124939/153300001-a1293a06-efeb-4775-ac4a-320d4c74040e.png)

 When I call `physicsWorld->destroyRigidBody(floorRigidBodyPtr) ` the box colliding with the floor should fall, but it does not. 

![image](https://user-images.githubusercontent.com/37124939/153300045-ade01804-bdd7-4572-9ac4-9f5bcc3859c4.png)

If I destroy the floor`s rigid body before the box hit it, the ploblem does not happen.  Is that intended behavior, or it is a bug?

**Comment by DanielChappuis** [comment]
Hello,

It could be a bug yes. It might be because the bodies are sleeping and the box is not awaken when the floor is destroyed. Could you try to wake up the box rigid body after the floor is destroyed using the following code?

`boxRigidBodyPtr->setIsSleeping(false);`

Does it work now?

**Comment by MatheusZickuhr** [comment]
> Hello,
> 
> It could be a bug yes. It might be because the bodies are sleeping and the box is not awaken when the floor is destroyed. Could you try to wake up the box rigid body after the floor is destroyed using the following code?
> 
> `boxRigidBodyPtr->setIsSleeping(false);`
> 
> Does it work now?

Hello, `boxRigidBodyPtr->setIsSleeping(false);` fixed it. Thanks!

**Comment by DanielChappuis** [comment]
Ok perfect but it is still a bug. I will need to fix this.
Thanks for reporting this.

**Comment by cpusam** [comment]
This kind of bug is too hard for me to solve it in my simple arcade physics.
For you don't wast so many time, I solve it like this:
1-add a vector of the position to the body when the world starts the update (preUpdate)
2-with the oldPosition, check after all bodies update (postUpdate) if the oldPosition, is nearly the currentPosition (updated one).
Nearly, I would say, the current position is "almost" the oldPosition, thinking like it is in a threshold.
It's aproximately like sleeping, but, it differs that you must check the threshold for each world update, what can be hard for many updated objects.

**Comment by DanielChappuis** [comment]
This is now fixed in version [v0.10.0](https://github.com/DanielChappuis/reactphysics3d/releases/tag/v0.10.0) of the library.
