### ISSUE TITLE
Ray.ray() doesn't hit non-solid ConcaveMesh

### ISSUE THREAD

**Issue by Trendyne** [DanielChappuis/reactphysics3d#236]
I'm trying to add FPS controls and need to check when the player is touching the floor. Level is a ConcaveMesh and a raycast didn't work on the flat-plane I was testing on

It's not a massive problem, but seems like it should work. It collides with solid objects just fine, so I think rays should too

Even using an extremely thin solid mesh (0.000046 m) gives me a hit, though it has an odd crash when I reach the edges of it, I'm guessing just floating point inaccuracy nonsense or something:
```
reactphysics3d/include/reactphysics3d/collision/narrowphase/NarrowPhaseInfoBatch.h:168: void reactphysics3d::NarrowPhaseInfoBatch::addContactPoint(reactphysics3d::uint32, const reactphysics3d::Vector3&, reactphysics3d::decimal, const reactphysics3d::Vector3&, const reactphysics3d::Vector3&): Assertion
contactNormal.length() > 0.8f' failed.
```

**Comment by Trendyne** [comment]
Seems to work now. Not sure what changed. I'll just reopen it if I find it

**Comment by DanielChappuis** [comment]
Hello. Thanks for your feedback. Yes, do not hesitate to reopen it if necessary.
