### ISSUE TITLE
HeapAllocator is not allocating pointers with 8 byte alignment

### ISSUE THREAD

**Issue by kencb** [DanielChappuis/reactphysics3d#239]
This is causing tons of memory errors right away just trying to create PhysicsCommon.
Has this library been tested on 64-bit at all?

**Comment by kencb** [comment]
Overall I want to say Thank you for RP3D. It looks a lot more light weight and easier to understand than Bullet, which I appreciate. Based on the demos I have a feeling Bullet has better performance but overall simpler code matters too.

**Comment by kencb** [comment]
More problems. This time it looks like it could potentially be a serious bug.

In `CollisionBodyComponents::allocate()`, the line:
`void** newUserData = reinterpret_cast<void**>(newIsActive + nbComponentsToAllocate);`
  
is causing `newUserData` to not be 8-byte aligned. It could even cause it to have an odd address depending on how many components are allocated if size of bool is 1, which is the case in my situation.

**Comment by kencb** [comment]
Unfortunately, as I suspected, fixing the alignment problems require a lot of changes and/or good knowledge of how the library works, so at this point I have to conclude that for my needs it's a no go.

**Comment by DanielChappuis** [comment]
You are right. I will need to fix those alignment issues for the next version of the library.

**Comment by DanielChappuis** [comment]
This is now fixed in version [v0.10.0](https://github.com/DanielChappuis/reactphysics3d/releases/tag/v0.10.0) of the library.
