### ISSUE TITLE
mIsDebugRenderingEnabled is not initialized

### ISSUE THREAD

**Issue by kencb** [DanielChappuis/reactphysics3d#240]
`PhysicsWorld::mIsDebugRenderingEnabled` is never explicitely initialized to a default value.

**Comment by DanielChappuis** [comment]
Thanks for reporting this.
I have fixed the issue in the 'develop' branch [here](https://github.com/DanielChappuis/reactphysics3d/commit/67f8e100f3742b5014722a0f44d8831898395c4d).

**Comment by kencb** [comment]
Thanks! The alignment issues are the real showstoppers though as it stands.

**Comment by DanielChappuis** [comment]
This is now fixed in version [v0.10.0](https://github.com/DanielChappuis/reactphysics3d/releases/tag/v0.10.0) of the library.
