### ISSUE TITLE
Wrap exceptions behind a define

### ISSUE THREAD

**Issue by mcela** [DanielChappuis/reactphysics3d#241]
Hello!

I think it might be useful to wrap these few throws behind `__cpp_exceptions` (or some other explicit `USE_EXCEPTIONS` define), since most game engines disable them, or remove them completely as there's asserts there anyways:

```
In file included from ./lib/reactphysics3d/include/reactphysics3d/memory/HeapAllocator.h:34:
./lib/reactphysics3d/include/reactphysics3d/containers/Map.h:386:29: error: cannot use 'throw' with exceptions disabled
                            throw std::runtime_error("The key and value pair already exists in the map");
                            ^
./lib/reactphysics3d/include/reactphysics3d/containers/Map.h:572:17: error: cannot use 'throw' with exceptions disabled
                throw std::runtime_error("No item with given key has been found in the map");
                ^
./lib/reactphysics3d/include/reactphysics3d/containers/Map.h:585:17: error: cannot use 'throw' with exceptions disabled
                throw std::runtime_error("No item with given key has been found in the map");

./lib/reactphysics3d/include/reactphysics3d/utils/DefaultLogger.h:364:25: error: cannot use 'throw' with exceptions disabled
                        throw(std::runtime_error("ReactPhysics3D Logger: Unable to open an output stream to file " + mFilePath));
```

Also a big thank you for creating the library! It's super useful to have a lightweight physics lib like this, and the code is very clear and readable. Opens a lot of doors.

**Comment by DanielChappuis** [comment]
Oh sorry. I just saw that I have never answered your question. Very sorry for that.

Anyway, thanks a lot for your feedback.

Yes, that's a good point. My goal is not to use exceptions in the ReactPhysics3D code. Therefore, I will see if I can improve that.

**Comment by DanielChappuis** [comment]
In the last version of the library (version [v0.10.0](https://github.com/DanielChappuis/reactphysics3d/releases/tag/v0.10.0)), I have removed the code throwing exceptions.
