### ISSUE TITLE
Setting cone limit for ball and socket joint off axis of bodies 1 and 2

### ISSUE THREAD

**Issue by GedaliaK** [DanielChappuis/reactphysics3d#242]
Hi,

I recently started learning your engine - pretty cool so far!

I was wondering if it is possible to set a cone limit that is not centered on the axis between the center of two bodies. For example, with a hip and leg connected by a joint, your leg can move more forward then back, and maybe a little more out than in. Is it possible to set up a cone limit in this way? Or alternatively, could you have two perpendicular  hinge joints connecting a hip and leg, since with the hinge joints can have different angle limitations for moving in positive and negative angles?

Thanks!

**Comment by DanielChappuis** [comment]
Hello. 

I am not really sure if I understand your setup correctly but currently, the cone limit of the ball-and-socket joint can only be setup between the 'anchor axes' of the two bodies. We consider that the 'anchor axis' is the axis between the center of mass of the body and the anchor point of the joint. The angle limit around the axis of the cone is perfectly symmetrical in every directions around the cone. Note that the center of mass of the body can be changed.

**Comment by DanielChappuis** [comment]
I am closing this issue. Do not hesitate to reopen it if needed.
