### ISSUE TITLE
RigidBody could benefit from getCenterOfMass methods

### ISSUE THREAD

**Issue by jagoly** [DanielChappuis/reactphysics3d#25]
Currently, it seems that the centre of mass cannot be retrieved from a RigidBody. In several cases, it can be useful to be able to retrieve the automatically generated value from the body to use elsewhere. Is there a reason that such functions don't exist, or am I missing something? It seems like they should, as there are functions to retrieve the mass and inertia tensor.

**Comment by DanielChappuis** [comment]
Yes that's a good idea. I will add this for the next release !

**Comment by DanielChappuis** [comment]
The version v0.8.0 of ReactPhysics3D has been released. In this version, there is now a RigidBody::getLocalCenterOfMass() method to get the location of the center of mass in local-space. There is also a RigidBody::getLocalInertiaTensor() method to retrieve the local-space inertia tensor.

Note that this version contains some public API changes. Please read carefully the change log  before upgrading to this new version and do not hesitate to take a look at the user manual.

I am therefore closing this issue.
