### ISSUE TITLE
VS2019 Unresolved external symbol

### ISSUE THREAD

**Issue by Fezezen** [DanielChappuis/reactphysics3d#253]
I'm not entirely sure if this is the place to even ask this question, but I cannot find any other information that is useful for this issue. Feel free to wave this away if it's irrelevant to the library.

I've been working on my own game engine in C++ and VS2019 and decided to use this library. I went through the building and installation process from the User Manual for Visual Studio. So now that I have the library build, I included the include directory in my VS project, the lib directory and I've linked the reactphysics3d.lib file in the linker.

No matter what I try I'm prompted with unresolved symbols:
![image](https://user-images.githubusercontent.com/35386815/167983507-2e6ded61-b6fd-41a9-9a67-43743c53d323.png)
(The _SDL_main stuff is irrelevant, trying this in a blank project without SDL2 doesn't work either)

I'm entirely lost and have absolutely no idea how to fix this. The library for sure is linked so I don't understand why this linking error occurs.

**Comment by DanielChappuis** [comment]
Hello. It really seems to be a linker issue. Can you post how you have set the include directories and libraries paths to the library in Visual Studio? Do you have screenshots?

**Comment by Fezezen** [comment]
So I have the include and library directories in my Program Files (x86) from the initialization process. And I've put the the include directory in the additional include directories tab in the project properties. 
![image](https://user-images.githubusercontent.com/35386815/168668112-a2e9aff7-1c56-4798-989f-df06e2b3d27a.png)

As well as the lib directory in the addition library directories tab
![image](https://user-images.githubusercontent.com/35386815/168668215-9afd8d7a-22bf-4a6a-abde-8e177c3aa6c2.png)

And of course the .lib file in the linker input
![image](https://user-images.githubusercontent.com/35386815/168668283-7b4f733c-9714-4bb8-9c3b-83131fac5c78.png)

**Comment by DanielChappuis** [comment]
It seems correct. The only difference on my side is that I set nothing in the _Linker->General_ menu but I give the absolute path to the .lib file in _Linker->Input_. How did you build the reactphysics3d.lib file ?

**Comment by Fezezen** [comment]
I tried the absolute path instead before. The way I built the lib file was by following the User manual. I installed CMake, downloaded the source, opened it in CMake and configured it to VS2019. Generated the files, then opened it VS2019, build the reactphysics3d solution in release, then built the INSTALL solution (With admin on). Nothing went wrong this entire time, it correctly placed the files in my program files.

**Comment by DanielChappuis** [comment]
Instead of using your code, can you try to build the '[Hello World](https://github.com/DanielChappuis/reactphysics3d/tree/master/helloworld)' sample of ReactPhysics3D?

You can try to build it using CMake (with the provided CMakeLists.txt file) or without it.

**Comment by Fezezen** [comment]
Seems to link completely fine with the helloworld sample.

**Comment by Fezezen** [comment]
Oh, could it be because in my other project I am compiling for x86 and not x64?

**Comment by DanielChappuis** [comment]
If you build the ReactPhysics3D library for x86 before using it (the .lib file) in your x86 project, it should be fine.

**Comment by DanielChappuis** [comment]
Have you been able to find the issue?

**Comment by Fezezen** [comment]
Oops. I forgot to close this. Sorry about that. I ended up not using Reactphyics in the project I intended to use it in, but I'm pretty sure compiling it to x86 would have fixed it.

**Comment by DanielChappuis** [comment]
No problem. Thanks for your feedback.
