### ISSUE TITLE
Code is working but no window?

### ISSUE THREAD

**Issue by vinniedaboi** [DanielChappuis/reactphysics3d#261]
I have used the CMake extension in vs code and the compiling has no warning or errors but there is just no window when I run the executable, any fixes for this?

**Comment by vinniedaboi** [comment]
<img width="753" alt="Screenshot 2022-06-25 at 10 15 42 AM" src="https://user-images.githubusercontent.com/86394697/175754443-6a32ee0e-a08e-47b2-ac50-de8630e68bc9.png">

**Comment by vinniedaboi** [comment]
`/*
 * This is a "hello world" project with a basic example of how to use
 * the ReactPhysics3D library in your project. This example is a simple
 * rigid body that is falling down because of gravity.
 */

// Libraries
#include <reactphysics3d/reactphysics3d.h>
#include <iostream>

// ReactPhysics3D namespace
using namespace reactphysics3d;

// Main function
int main() {

    // First you need to create the PhysicsCommon object. This is a factory module
    // that you can use to create physics world and other objects. It is also responsible
    // for logging and memory management
    PhysicsCommon physicsCommon;

    // Create a physics world
    PhysicsWorld* world = physicsCommon.createPhysicsWorld();

    // Create a rigid body in the world
    Vector3 position(0, 20, 0);
    Quaternion orientation = Quaternion::identity();
    Transform transform(position, orientation);
    RigidBody* body = world->createRigidBody(transform);

    const decimal timeStep = 1.0f / 60.0f;

    // Step the simulation a few steps
    for (int i=0; i < 20; i++) {

        world->update(timeStep);

        // Get the updated position of the body
        const Transform& transform = body->getTransform();
        const Vector3& position = transform.getPosition();

        // Display the position of the body
        std::cout << "Body Position: (" << position.x << ", " << position.y << ", " << position.z << ")" << std::endl;
    }

    return 0;
}`

**Comment by DanielChappuis** [comment]
Hello. Thanks for your question.

The 'hello world' example is a very simple project with a rigid body that is falling down. This program only displays the position
of the rigid body in the console, that's it. Therefore, it seems to be working perfectly in your case if I take a look at your screenshot.

If you want to see visual examples of the library, you need to compile the '[testbed](https://reactphysics3d.com/usermanual.html#x1-7500014)' application. This application contains many physics demos.

**Comment by DanielChappuis** [comment]
I am closing this issue. Do not hesitate to reopen if something is not clear.
