### ISSUE TITLE
Floor made up of tiles doens't have smooth movement over it

### ISSUE THREAD

**Issue by Omroth** [DanielChappuis/reactphysics3d#266]
Hiya,

My floor is made up of cuboid tiles, but they all have the same height.  When I move an object over it, be it a sphere or another cuboid, there is often a hitch or a jump as it navigates between tiles, even though they line up.

What's my best approach to this?  Would expanding them a bit so they definitely overlap be a better idea?

**Comment by DanielChappuis** [comment]
I would say that this is expected from the collision detection when moving between different collision shapes. You should try to use a single collision shape that contains all your floor in your case. Either a BoxShape, or maybe a ConvexMeshShape or a ConcaveMeshShape instead.

**Comment by Omroth** [comment]
I guess a ConcaveMeshShape would allow me to have many floors in them?

**Comment by DanielChappuis** [comment]
I am closing this issue. Do not hesitate to reopen it if needed.
