### ISSUE TITLE
Warning on c++20 build (emscripten)

### ISSUE THREAD

**Issue by caxapexac** [DanielChappuis/reactphysics3d#275]
```
In file included from include/reactphysics3d/reactphysics3d.h:42:
In file included from include\reactphysics3d/engine/PhysicsCommon.h:31:
In file included from include\reactphysics3d/engine/PhysicsWorld.h:45:
include\reactphysics3d/collision/OverlapCallback.h:99:30: warning: explicitly defaulted copy assignment operator is implicitly deleted [-Wdefaulted-function-deleted]
                OverlapPair& operator=(const OverlapPair& contactPair) = default;
                             ^
include\reactphysics3d/collision/OverlapCallback.h:78:30: note: copy assignment operator of 'OverlapPair' is implicitly deleted because field 'mContactPair' is of reference type 'reactphysics3d::ContactPair &'
                ContactPair& mContactPair;
```

I can provide any additional info which could help to locate this warning build configuration, is it needed?

**Comment by DanielChappuis** [comment]
Thanks for reporting this. I will try to fix this in the next release.

**Comment by caxapexac** [comment]
Oh huge thanks for such a speed :)

**Comment by DanielChappuis** [comment]
This is now fixed in version [v0.10.0](https://github.com/DanielChappuis/reactphysics3d/releases/tag/v0.10.0) of the library. Thanks a lot for reporting the issue.

**Comment by caxapexac** [comment]
@DanielChappuis thanks for the fix. Btw several days ago I've tried to update myself to the develop branch of the engine because of https://github.com/DanielChappuis/reactphysics3d/issues/366
But ended up making those iterator changes manually instead of updating (updating to 'develop' caused another different crash to happen). I'll create the issue on a new crash as soon as I get some time (it didn't crash on a current release, something on a broad phase probably iirc, when I forcefully change the translation of an object)

**Comment by DanielChappuis** [comment]
@caxapexac Yes, if you could open a new issue with a stack trace, it would be great.
