### ISSUE TITLE
coredump maybe 

### ISSUE THREAD

**Issue by hustmzy** [DanielChappuis/reactphysics3d#276]
hello.
I have compiled the code in ubuntu18.04 and successfully generate the bin file testbed in the path "build/testbed".
When I run the testbed like "./testbed" it directly cored dump. 
The gdb results:
#0  0x000056494265864c in reactphysics3d::PhysicsCommon::createPhysicsWorld(reactphysics3d::PhysicsWorld::WorldSettings const&) ()
#1  0x00005649425ebf52 in raycastscene::RaycastScene::RaycastScene(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, EngineSettings&, reactphysics3d::PhysicsCommon&) ()
#2  0x00005649425c47c6 in TestbedApplication::createScenes() ()
#3  0x00005649425c506f in TestbedApplication::start() ()
#4  0x00005649425b90ff in main ()

Is there anything wrong with my operation？Many thanks.

**Comment by DanielChappuis** [comment]
I am closing this issue. If you have any news, feel free to reopen it.
