### ISSUE TITLE
FixedJoint (and SliderJoint) don't seem to work when bodies are rotated with non-identity transform

### ISSUE THREAD

**Issue by jrouwe** [DanielChappuis/reactphysics3d#28]
Hello,

I'm trying to implement the Fixed/Slider joint as described in your article: 

http://danielchappuis.ch/download/ConstraintsDerivationRigidBody3D.pdf

and I'm running into issues trying to implement the rotation constraint when the bodies have an initial relative rotation other than identity (mInitOrientationDifferenceInv != identity). 

I then tried the same in your code to see what happens and it looks like it has the same problem. If you add the following lines in JointsScene::createFixedJoints:

...
mFixedJointBox1 = new Box(boxDimension, positionBox1 , BOX_MASS, mDynamicsWorld);

// NEW CODE!
rp3d::Vector3 initPosition(5, 7, 0);
rp3d::Quaternion initOrientation = rp3d::Quaternion(0.4f * PI, 0, 0);
rp3d::Transform transform(initPosition, initOrientation);
mFixedJointBox1->getRigidBody()->setTransform(transform);

// Set the box color
...

You will see that the box that is being spinned around on the propeller starts jittering heavily (the closer you get to half PI the more is starts to jitter, but a rotation of 0.1f * PI misbehaves too).

I have the feeling that eq 129 is not the same as SliderJoint.cpp:

const Vector3 errorRotation = decimal(2.0) * qError.getVectorV();

So far I've been unable to put my finger on what is going wrong. Do you have any idea?

Regards,

Jorrit.

**Comment by jrouwe** [comment]
What I forgot to mention is that the problem is in FixedJoint::solvePositionConstraint. If you comment out the entire block under:

// --------------- Rotation Constraints --------------- //

the jitter is gone (but obviously the body rotation will start to drift eventually).

**Comment by jrouwe** [comment]
Hello,

I created a fix for the bug and created a pull request for you:

https://github.com/DanielChappuis/reactphysics3d/pull/29

Derivation of the (hopefully) correct equations are in the source code.

Note that I only tested this on the FixedJoint, and only for the situation where mPositionCorrectionTechnique == NON_LINEAR_GAUSS_SEIDEL. 

I also typed in the same code for the SliderJoint and when mPositionCorrectionTechnique == BAUMGARTE_JOINTS.

**Comment by jrouwe** [comment]
I also hacked in some extra fixed bodies in the JointsScene (you probably don't want to integrate but nice for verifying that it works):

https://github.com/jrouwe/reactphysics3d/commit/6e5f067cdadd98c7a1f371dbb9a68cba05ce4f77

**Comment by DanielChappuis** [comment]
Thanks a lot for your work. 

I will check your pull request on Monday or Tuesday when I have some time. When I was able to reproduce the issue 2 days ago I suspected that something was wrong with the way I compute the orientation difference between the bodies.

**Comment by DanielChappuis** [comment]
I have cherry-picked the commit that fixes the bug in your pull request and I have merged the following commit : 1855e1c121772bad22e68fe9da077d0b089739ee into the master branch.

Thanks a lot for reporting and fixing this issue.
