### ISSUE TITLE
About simulate a fragile object

### ISSUE THREAD

**Issue by zack-not-know-why-it-work** [DanielChappuis/reactphysics3d#289]
Hi Daniel,

I want to simulate a fragile object.   if other object hit this object with big Force(or fast Velocity), the fragile object will broke into pieces, otherwise the object is a normal rigid body.

Currently I have not write any code to test. My basic idea is two parts for fragile object: a normal rigid body and a trigger around it. When the trigger is triggered,   calculate the velocity of hitting object, if it bigger than the limit velocity, then play the broke into pieces animation.

I want to known if my idea is ok. Do you have any advice?  Thank you.

**Comment by DanielChappuis** [comment]
Yes that might work. An other solution (if you don't want to play an animation but let the physics do its job) is to have two rigid bodies connected with a fixed joint. If the hitting velocity is high enough you manually break the joint and the two bodies will automatically fall apart (depending of their shapes and positions).

**Comment by DanielChappuis** [comment]
I am closing this issue. Feel free to open a new discussion instead if still necessary.
