### ISSUE TITLE
Axis constraints to lock position/rotation

### ISSUE THREAD

**Issue by haikarainen** [DanielChappuis/reactphysics3d#33]
Do this functionality exist? If not, how much work would you recon it would take to get it going? 

For example, check this screenshot from UE4

![UE4 physics](https://answers.unrealengine.com/storage/temp/64547-capture.png)

**Comment by saucecode** [comment]
Hi, I also wanted this feature. I'm not a fantastic C++ programmer, and I've never worked on physics engines, but I tried my hand at implementing the feature. It works well enough for my purposes. I took inspiration from issue #21.

Here's a [patchfile](https://gist.githubusercontent.com/saucecode/e42a28ece6146aa08091fedcde0ddf18/raw/ddb06d31bf9c47c2215b989b9172aebdacaa263d/velocity-constraints.patch) of what I did, and my [fork](https://github.com/saucecode/reactphysics3d).

**Comment by DanielChappuis** [comment]
Hello. Yes I plan to add this in the future. I am currently working on multithreading the engine.

Thanks a lot for your patchfile. This could help me when I will implement this feature.

**Comment by maluoi** [comment]
I'd also be interested in this!

**Comment by KineticTactic** [comment]
Has this feature been implemented in v0.8.0?

**Comment by DanielChappuis** [comment]
Hello,
Sorry, this feature is not part of v0.8.0.
I plan to add it in version v0.9.0.

I don't currently see a way to implement this for the moment.

**Comment by DanielChappuis** [comment]
I glad to announce that this feature is now implemented in version [v0.9.0](https://github.com/DanielChappuis/reactphysics3d/releases/tag/v0.9.0) that has just been released.

There is now a `RigidBody::setLinearLockAxisFactor()` method to lock the translational movement of a body along the world-space x, y and z axes and a `RigidBody::setAngularLockAxisFactor()` method to lock the rotational movement of a body around the world-space x, y and z axes.

Do not hesitate to take a look at the [documentation](https://reactphysics3d.com/documentation.html) for more information.
