### ISSUE TITLE
Get all objects overlapped by sphere

### ISSUE THREAD

**Issue by ghost** [DanielChappuis/reactphysics3d#342]
I'd like to find all objects within a sphere in the dworld.  Best way I've found is to PhysicsWorld::testOverlap but that involves adding a CollisionShape to a Body to get a Collider - is there not a quicker way?

**Comment by DanielChappuis** [comment]
Yes sorry that is currently the way to do it. I plan to simplify this in the future to have better API to perform world queries.

**Comment by DanielChappuis** [comment]
I am closing this issue. Do not hesitate to reopen it if necessary.
