### ISSUE TITLE
Bounciness

### ISSUE THREAD

**Issue by Omroth** [DanielChappuis/reactphysics3d#345]
I'm setting:

collider->getMaterial().setBounciness(0.0)

On my colliders, and they still bounce a lot.  Any ideas?

**Comment by DanielChappuis** [comment]
In a contact between two bodies the largest bounciness factor of the two colliders is used. Therefore, if you want no bounciness at all in a contact, you need to set the bounciness factor of both colliders to zero.

**Comment by Omroth** [comment]
Thanks, that helps me fix my problem.  Did you consider taking an average instead out of interest?
