### ISSUE TITLE
Are different dworlds threadsafe?

### ISSUE THREAD

**Issue by ghost** [DanielChappuis/reactphysics3d#346]
Can I use two different dworlds from the same PhysicsCommon on different threads with no mutexing?

**Comment by DanielChappuis** [comment]
Multi-threading is not currently supported by the library. I hope to work on that soon.

**Comment by Omroth** [comment]
Thank you.  Could I currently use two PhysicsCommons, on different threads?

**Comment by DanielChappuis** [comment]
You can try but there are some static fields in the PhysicsCommon class and you could have issues with that if you instanciate two instances.

**Comment by DanielChappuis** [comment]
I am closing this issue. Feel free to open a new discussion if needed.
