### ISSUE TITLE
CollisionDetectionSystem::createContacts() assert crash

### ISSUE THREAD

**Issue by darktemplar216** [DanielChappuis/reactphysics3d#364]
in void CollisionDetectionSystem::createContacts() {

by using triggers in the game, I found that the assertion below fails

> 
    for (uint32 p=0; p < nbContactPairsToProcess; p++) {
        uint32 contactPairIndex = mWorld->mProcessContactPairsOrderIslands[p];
        ContactPair& contactPair = (*mCurrentContactPairs)[contactPairIndex];
	...
        
       assert(potentialManifold.nbPotentialContactPoints > 0);

After I went through the code, I think we are not generating contact points for the triggers. So I add a if() continue to prevents it from happenning.

> 
    for (uint32 p=0; p < nbContactPairsToProcess; p++) {
        uint32 contactPairIndex = mWorld->mProcessContactPairsOrderIslands[p];
        ContactPair& contactPair = (*mCurrentContactPairs)[contactPairIndex];
	...
        
        if (contactPair.isTrigger)
        {
            continue;
        }

So far seems fine
Does it make any sense? Daniel

**Comment by DanielChappuis** [comment]
Hello. Thanks a lot for reporting this issue. I take some time to take a look and I think this is already fixed in the "develop" branch. This will be available in the next release of the library.

**Comment by DanielChappuis** [comment]
This is now fixed in version [v0.10.0](https://github.com/DanielChappuis/reactphysics3d/releases/tag/v0.10.0) of the library. Thanks a lot for reporting the issue.
