### ISSUE TITLE
Transform::getOpenGLMatrix not including rotation

### ISSUE THREAD

**Issue by TheBoneJarmer** [DanielChappuis/reactphysics3d#365]
Hey

In my desperate attempt to retrieve the rotation axis I figured I could consider extracting the data from the transformation matrix. However, when I run the method `Transform::getOpenGLMatrix` I only see the last row getting values (the position). I would expect the rotation to be included as well.

With kind regards,
TheBoneJarmer

**Comment by DanielChappuis** [comment]
Hello. As you can see [here](https://github.com/DanielChappuis/reactphysics3d/blob/17dd22e677ed861b0d4ece0c00a7e3cb503cc2f0/src/mathematics/Transform.cpp#L43) in the code, both the orientation and position are returned by the `Transform::getOpenGLMatrix()` method.

**Comment by DanielChappuis** [comment]
I closing this issue. Feel free to open a new discussion instead if this is still not clear.
