### ISSUE TITLE
void PhysicsWorld::createIslands() dirty contactPairIndex crash

### ISSUE THREAD

**Issue by darktemplar216** [DanielChappuis/reactphysics3d#366]
in void PhysicsWorld::createIslands()

> 
            const uint32 nbBodyContactPairs = static_cast<uint32>(mRigidBodyComponents.mContactPairs[bodyToVisitIndex].size());
            for (uint32 p=0; p < nbBodyContactPairs; p++) {

                const uint32 contactPairIndex = mRigidBodyComponents.mContactPairs[bodyToVisitIndex][p];
                ContactPair& pair = (*mCollisionDetection.mCurrentContactPairs)[contactPairIndex];

When using Trigger and RigidBody together, sometimes mRigidBodyComponents.mContactPairs contain dirty indices from the old frames and indexing mCollisionDetection.mCurrentContactPairs crashes the program by hitting the Assertion inside Array.

Seems that only cleaning the Enabled RigidBodyComponents leaves the dirty data behind

>     
     const uint32 nbRigidBodyEnabledComponents = mRigidBodyComponents.getNbEnabledComponents();
     for (uint32 b=0; b < nbRigidBodyEnabledComponents; b++) {
         mRigidBodyComponents.mContactPairs[b].clear();
     }

I change this loop to all rigidbodyComponents 

> 
	for (uint32 b = 0; b < nbRigidBodyComponents; b++) {
		mRigidBodyComponents.mContactPairs[b].clear();
	}

seems everything's fine and prevented the crash.

Does it makes any sense to you? Daniel.

**Comment by DanielChappuis** [comment]
Thanks a lot for reporting this. I will take a look at this as soon as I have some time.

**Comment by darktemplar216** [comment]
Thanks, dude, nobody knows this lib better than you. Thumbs up

**Comment by DanielChappuis** [comment]
This issue is already fixed by some refactoring I did in the 'develop' branch. This will be part of the next release of the library. Again, thanks a lot for reporting the issue and for the fix also.

**Comment by DanielChappuis** [comment]
This is now fixed in version [v0.10.0](https://github.com/DanielChappuis/reactphysics3d/releases/tag/v0.10.0) of the library. Thanks a lot for reporting the issue.
