### ISSUE TITLE
Will it work for Android?

### ISSUE THREAD

**Issue by VadimBoev** [DanielChappuis/reactphysics3d#367]
Hello.  
I am looking for a physics engine with a purpose for the Android platform.   
Will this engine work on armeabi-v7a and arm64 ?   
How are things going with optimization?   
Is it heavily loading the processor?

**Comment by DanielChappuis** [comment]
Hello. I have personally never try to run the library on Android. Therefore, I cannot really promise that it will work without any issue.

About optimization and loading the processor, it really depends on the device and on your simulation.

**Comment by VadimBoev** [comment]
thanks for the answer!
