### ISSUE TITLE
Doesn't install anything

### ISSUE THREAD

**Issue by yurivict** [DanielChappuis/reactphysics3d#37]
cmake-based projects are usually expected to install the project into ```$DESTDIR/$PREFIX```.

**Comment by DanielChappuis** [comment]
Hello. Yes "make install" is not implemented yet. What kind of behavior do you want ? Installing the compiled library somewhere in your system ? Installing the testbed application ? Both ?

**Comment by yurivict** [comment]
Installing library/headers under ```$DESTDIR/$PREFIX```.

**Comment by DanielChappuis** [comment]
Thanks. I will try to implement this.

**Comment by yurivict** [comment]
You can look at any other cmake project. cmake has ```INSTALL``` instructions, that's all that needs to be done. headers/libraries/man pages/icons are installed.

**Comment by DanielChappuis** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add instal target in CMake file to install the compiled library and header on the system](https://trello.com/c/Mt9abtCd/47-add-instal-target-in-cmake-file-to-install-the-compiled-library-and-header-on-the-system)

**Comment by DanielChappuis** [comment]
This is now done in the version v0.7.0 of ReactPhysics3D that has just been released.
Thanks a lot for reporting this.

**Comment by yurivict** [comment]
Now the version ```0.7.0``` only installs ```lib/libreactphysics3d.a``` and no headers.

**Comment by yurivict** [comment]
Also, ```ADD_LIBRARY(reactphysics3d STATIC ${REACTPHYSICS3D_HEADERS} ${REACTPHYSICS3D_SOURCES})``` always installs the static library. Usually, cmake projects use the ```BUILD_SHARED_LIBS``` option to control the type of library to build: https://cmake.org/cmake/help/v3.0/variable/BUILD_SHARED_LIBS.html

**Comment by yurivict** [comment]
This prevents me from creating a FreeBSD port for reactphysics3d
.

**Comment by yurivict** [comment]
Now it installs headers and the shared library. One problem: the library shouldn't be in a subdirectory: ```lib/reactphysics3d/libreactphysics3d.so``` should be ```lib/libreactphysics3d.so```.

**Comment by DanielChappuis** [comment]
That's right. I have just pushed a fix in the same branch.
Can you test if it is ok now ?

**Comment by yurivict** [comment]
Yes, it's fine now.

One thing that can be further improved is to create symbolic links for the shared library:
```
libreactphysics3d.so.0.7.0 -> libreactphysics3d.so
libreactphysics3d.so.0.7 -> libreactphysics3d.so
libreactphysics3d.so.0 -> libreactphysics3d.so
```

```libreactphysics3d.so.0``` or ```libreactphysics3d.so.0.7``` should be a SONAME. Any incompatible, non-incremental changes to the interface should trigger the SONAME change.

**Comment by DanielChappuis** [comment]
I have just added the VERSION and SOVERSION to the CMakeLists.txt with this [commit](https://github.com/DanielChappuis/reactphysics3d/commit/f86038aa31875daacc2d950be7b999c0d6a19986) in the [fix37](https://github.com/DanielChappuis/reactphysics3d/tree/fix37) branch. 

Is it what you expect ?

**Comment by yurivict** [comment]
Yes, this is exactly what I've asked for!
Thanks!

**Comment by DanielChappuis** [comment]
Thanks for reporting this. I have just merged the fix37 branch with the fix into master.
