### ISSUE TITLE
Ticking different objects at different rates

### ISSUE THREAD

**Issue by ghost** [DanielChappuis/reactphysics3d#380]
Hi,

I have a class of less important objects which I do not need as much simulation accuracy on.  Is it possible to tick those "more cheaply"?

Thanks

**Comment by DanielChappuis** [comment]
Hello. Sorry for late answer. It is not currently possible to do this.

Can I please ask you next time to open a new [Discussion](https://github.com/DanielChappuis/reactphysics3d/discussions) instead of creating an issue? Thanks a lot.

**Comment by DanielChappuis** [comment]
I am closing this issue. Create a new discussion if needed.
