### ISSUE TITLE
find mistake in code 

### ISSUE THREAD

**Issue by nustxujun** [DanielChappuis/reactphysics3d#387]
in createConvexMesh , convex mesh  will be released by heapallocator when failed . I think it should be released by mMemoryManager, right?

**Comment by DanielChappuis** [comment]
Thanks a lot for your feedback. Yes, you are right !
I will fix that in the next release of the library.

**Comment by DanielChappuis** [comment]
This issue should now be fixed in release of version [v0.10.1](https://github.com/DanielChappuis/reactphysics3d/releases/tag/v0.10.1). Thanks again for reporting this issue.
