### ISSUE TITLE
Rigid bodies without colliders escape from joint with a rigid body with collider.

### ISSUE THREAD

**Issue by robertocapuano** [DanielChappuis/reactphysics3d#388]
I create a chain of rigid bodies with a colliders interleaved with a rigid bodies without colliders, they are connected via slider joint and ball and socket joints. The last element is a rigid body without collider linked by a fixed joint to the last rigid body with a collider. I apply a force on this last one.

Sometimes it happens that the body escapes the joint and returns to position only by moving the first object.

Below is a snippet of code of the last two bodies to make the example clearer:

RP3D::RigidBody *body1 = m_world->createRigidBody( { pos1, QUAT_I }  );
RP3D::CollisionShape* shape =m_common.createSphereShape( radius ); 
Fx::ColliderRef coll = m_world->  createCollider( body1, shape, Fx::Transform {} );
body1->addCollider( shape, Fx::Transform {} );

RP3D::Transform tr { pos2, QUAT_I };
Fx::RigidBodyRef body2 = m_world->createRigidBody  ( tr );

const RP3D::Transform &tr1 = body1->getTransform();
const RP3D::Transform &tr2 = body2->getTransform();
const RP3D::Vector3 anchor_point = .5f * ( tr1.getPosition() + tr2.getPosition() );

RP3D::FixedJointInfo jointInfo(body1, body2, anchor_point );
RP3D::FixedJoint *joint = (RP3D::FixedJoint*) m_world->createJoint(jointInfo);

**Comment by robertocapuano** [comment]
This commit causes the problem:
https://github.com/DanielChappuis/reactphysics3d/commit/92a118cb38fc4a9953d3892f9bd6f1f7a5b4d050

**Comment by robertocapuano** [comment]
This commit breaks the functionality:
https://github.com/DanielChappuis/reactphysics3d/commit/8f46764e4bc5e7a60e028accb4ce2f6d0ab8ec47

**Comment by DanielChappuis** [comment]
This issue should now be fixed in release of version [v0.10.1](https://github.com/DanielChappuis/reactphysics3d/releases/tag/v0.10.1). Thanks again for reporting this issue.
