### ISSUE TITLE
Networked Physics

### ISSUE THREAD

**Issue by kklouzal** [DanielChappuis/reactphysics3d#39]
Would this library be suitable in a networked environment where multiple clients share an approximation of a singular host simulation?

**Comment by DanielChappuis** [comment]
Hello. I am not very familiar with networked simulations with multiple clients and I never tried to use ReactPhysics3D for this purpose but I do not see why it would not be possible.

**Comment by kklouzal** [comment]
Often the most appropriate way to make a coherent shared simulation across a network you must be able to 'rewind' the physics to a previous point in time, make an adjustment to a rigid body (albeit  velocity/position/etc..), then 'replay' the simulation up to the current point in time.

When a client receives an update from the server or vise versa this update is always something that has happened in the past (due to latency introduced across the network), so the rewind-replay method is almost a must.
