### ISSUE TITLE
Missing collision resolving/reporting for some static rigid bodies with dynamic rigid bodies.

### ISSUE THREAD

**Issue by andreasdr** [DanielChappuis/reactphysics3d#49]
Hi,

I am integrating RP3D 0.7.0 into my 3d engine TDME2. Everythings starts to work. This is nice.

But I have issues with some static rigid bodies that do not seem to be taken into account if a dynamic rigid body collides with them.

I have an example video where you can see the issue:
-  https://www.youtube.com/watch?v=hCFecUVEDQs&feature=youtu.be

I have extracted a simple test case using capsules here:
- https://github.com/andreasdr/tdme2/blob/reactphysics3d-current/src/tdme/tests/PhysicsTest4.cpp

It spawns 6 static capsules(with a height of 20m) and 2 dynamic(one small, one bigger) which can be moved by arrow keys. The place where the big dynamic capsule spawns 2 of those 6 static capsules will be used for collisions, all the others not - if you move the dynamic rigid bodies into them. You can change the code easily to spawn those 6 static capsules as dynamic and then all works.

Related files for capsule, creating rigid bodies and world management can be seen here:
- https://github.com/andreasdr/tdme2/blob/reactphysics3d-current/src/tdme/engine/primitives/Capsule.cpp
- https://github.com/andreasdr/tdme2/blob/reactphysics3d-current/src/tdme/engine/physics/World.cpp
- https://github.com/andreasdr/tdme2/blob/reactphysics3d-current/src/tdme/engine/physics/RigidBody.cpp

My observations:
- this seem to happen with larger static rigidbodies/objects
- collision is computed if another larger dynamic rigid body is spawned at near by positions of those static rigid bodies
- collision is computed if I spawn those static rigid bodies as dynamic rigid bodies(also setting a non rotation inertia inverse tensor(not sure about the name) and infinite mass (then they behave like static objects, but computation of large world is not working anymore performance wise)
- I have debugged and tried a lot(RP3D AABBs seem correct, capsule height and radius seem correct, ...)

If you have any questions please do not hesitate to ask. 
BTW. If spawning them all as dynamic rigid bodies like described above all my problems seem to be gone with our game prototype. So maybe its a stupid issue only.

I am looking forward to hearing from you soon:

Best regards
Andreas

**Comment by andreasdr** [comment]
Hi,

I have a workaround that seems to work 100%.
I add the static rigid bodies as dynamic ones like described above. 
And after first world.update() I set them to static. 

Works perfekt.

Best regards
Andreas

**Comment by andreasdr** [comment]
Hi,

forget about this bug. Looks like i passed transformations matrix with scale to RP3D. This seem to produce this weird bug.

`transform.setFromOpenGL(transformationsMatrix.getArray().data());`

Now i normalize the quaternion by using:
```
	// normalize orientation to remove scale
	auto transformOrientation = transform.getOrientation();
	transformOrientation.normalize();
	transform.setOrientation(transformOrientation);
```

I was scaling capsules, ... on my own already and I guess using scale with your quaternions are not supported which would mean double scale as well.

Best regards
Andreas

**Comment by DanielChappuis** [comment]
Yes, scaling is not supported in the ReactPhysics3D transforms. This is the case in other physics engines as you can see [here](https://gamedev.stackexchange.com/questions/90767/bullet-physics-scaling) for instance.

I am glad that you solved your issue. Therefore, I am closing this one.
