### ISSUE TITLE
Hit an assert in CollisionBody::~CollisionBody

### ISSUE THREAD

**Issue by andreasdr** [DanielChappuis/reactphysics3d#52]
Hi,

I am hitting an assert when destroying a collision body in a dynamics world.

Assertion failed: (mContactManifoldsList == nullptr), function ~CollisionBody, file ext/reactphysics3d/src/body/CollisionBody.cpp, line 54.

See:
- https://github.com/andreasdr/tdme2/blob/reactphysics3d-current/src/tdme/engine/physics/RigidBody.cpp
- https://github.com/andreasdr/tdme2/blob/reactphysics3d-current/src/tdme/engine/physics/World.cpp

Best regards
Andreas

**Comment by andreasdr** [comment]
JFI: I am adding a collision body in a frame and then just remove it after several frames(means after several world.update() calls). So nothing special at all.

**Comment by DanielChappuis** [comment]
I think I have fixed this issue with this [commit](https://github.com/DanielChappuis/reactphysics3d/commit/d15a41f0ccd22bd338de41879cf41664e501dd28) in the **develop** branch.

Can you confirm that it is also fixed on your side in the **develop** branch ?

**Comment by andreasdr** [comment]
Hi,

This seem to work! Thank you.

Best regards
Andreas

**Comment by andreasdr** [comment]
Seems to be fixed. Thank you.

**Comment by DanielChappuis** [comment]
Ok Thanks. The fix is now merged in the master branch.
