### ISSUE TITLE
Small bug fix with compiling on MinGW64

### ISSUE THREAD

**Issue by andreasdr** [DanielChappuis/reactphysics3d#54]
Hi,

I just had a problem when compiling RP3D on Windows 10 with MINGW64.
Please see attached a commit to fix this (in my TDME2-RP3D branch)

- https://github.com/andreasdr/tdme2/commit/54c1ee70af96c2e7cb1580c7afbd9132e2e896e8#diff-2f8127ed8f66b3d3f4e5a8d3fcec24a4

Best regards
Andreas

**Comment by DanielChappuis** [comment]
Ok Thanks. The fix is now merged in the master branch.
