### ISSUE TITLE
Linker error

### ISSUE THREAD

**Issue by andreasdr** [DanielChappuis/reactphysics3d#55]
Hi,

I have found a simple linker error which is easy to fix: 

Have a look at
- https://github.com/DanielChappuis/reactphysics3d/blob/master/src/engine/CollisionWorld.cpp#L253

There you specify "inline" to a CPP definition, thats why its code is not generated in library. But as inline is not in header its also not inline compiled.

Removing the "inline" fixes the error.

Best regards
Andreas

**Comment by DanielChappuis** [comment]
Thanks. The fix is now merged in the master branch.
