### ISSUE TITLE
Question about CollisionWorld::testAABBOverlap

### ISSUE THREAD

**Issue by andreasdr** [DanielChappuis/reactphysics3d#58]
Hi,

I would like to know if

`CollisionWorld::testAABBOverlap(const AABB& aabb, OverlapCallback* overlapCallback, unsigned short categoryMaskBits)`

does "AABB <> rigidbody AABB" tests or "AABB <> rigidBody CollisionShape(s)" tests?

I have one case where I am using this to test if a player can be spawned with ConcaveMeshShape(Terrain) and other Players(Capsule) in world, ...
It returns collision with ConcaveMeshShape whereas there should not be any.

Best regards
Andreas

**Comment by DanielChappuis** [comment]
I have made the comment of this method more clear in the code. I am closing this issue.
