### ISSUE TITLE
Assert with Joints

### ISSUE THREAD

**Issue by liuqiangNetease** [DanielChappuis/reactphysics3d#63]
assert(island->getNbJoints() > 0);

when one Scene has three bodys: a HingeJoint(connect two righidbody) and a righidbody without HingeJoint.

**Comment by liuqiangNetease** [comment]
solvePositionConstraints(reactphysics3d::Island*)
DynamicsWorld::solvePositionCorrection()
DynamicsWorld::update(float)

**Comment by liuqiangNetease** [comment]
hello,
  the bug is 100% appear, when scene has three bodies.  a HingeJoint(connect two righidbody) and a righidbody without HingeJoint.

**Comment by DanielChappuis** [comment]
Can you post here the code you use to create the bodies, the joints and to add them into the world ?

**Comment by liuqiangNetease** [comment]
ok,  add codes below( test begin, end)  in JointsScene::JointsScene(). constructor function. 

// Create the dynamics world for the physics simulation
    mPhysicsWorld = new rp3d::DynamicsWorld(gravity, worldSettings);
          
          
          //test crash by lq begin
          Box* cube = new Box(BOX_SIZE, BOX_MASS, getDynamicsWorld(), mMeshFolderPath);

          // Change the material properties of the rigid body
          rp3d::Material& material = cube->getRigidBody()->getMaterial();
          material.setBounciness(rp3d::decimal(0.4));
          //end

    // Create the Ball-and-Socket joint
    createBallAndSocketJoints();

**Comment by DanielChappuis** [comment]
I have pushed the [fix63](https://github.com/DanielChappuis/reactphysics3d/tree/fix63) branch with a fix for this issue. Can you please test this branch on your side and let me know if it is fixed on your side ?

**Comment by liuqiangNetease** [comment]
thank u, it works.

**Comment by DanielChappuis** [comment]
I have merged the fix into the "master" branch. Thanks a lot for reporting this issue.
