### ISSUE TITLE
simulation Gravity and bouniness

### ISSUE THREAD

**Issue by liuqiangNetease** [DanielChappuis/reactphysics3d#64]
when a rigidbody (give  material bouniness, something like 0.8f ),   the body down to the floor because of gravity,    the body up and down even when the body has litter higher than floor.  
 As my experience， and in PhyX, the body will be still instead of dithering.

**Comment by DanielChappuis** [comment]
Hello,

I am sorry but I did not really understand what is going on. Can you please explain precisely what happens ?

**Comment by liuqiangNetease** [comment]
hi,
 I cannot reappear the problem. when it reappear,  I try to describe in details.

**Comment by DanielChappuis** [comment]
I am closing this issue because it is quite old and it might already be fixed in the last versions of the library. Feel free to reopen if that's not the case
