### ISSUE TITLE
Question about  EventListener

### ISSUE THREAD

**Issue by liuqiangNetease** [DanielChappuis/reactphysics3d#66]
hello!
1.  How Can I implement OnCollisionEnter(),  OnCollisionExit();  OnCollisionStay(), OnTriggerEnter(),  OnTriggerExit();  OnTriggerStay()   as the same with unity3d?

**Comment by DanielChappuis** [comment]
You are right, this section of the documentation does not seem up to date. I will update it. Currently, the EventListener class only supports the newContact() callback that is called for each contact found during a frame (each call to DynamicsWorld::update()). For instance, if a box is resting on another box with 4 contact points, you will have each frame a newContact() callback with the 4 contact points.

Could you please briefly explain the different callbacks from Unity3D that you would need and when they are called exactly ?

**Comment by liuqiangNetease** [comment]
OnCollisionEnter equals beginContact
OnCollisionExit equals endContact
OnCollisionStay equals newContact
A Collider(or shape), which have a property called isTrigger, if a collider has property  isTrigger,  it will not collider with others(no physics),  but you can rayCast it.

**Comment by DanielChappuis** [comment]
I will try to add more collision feedback in the EventListener in the future.

**Comment by DanielChappuis** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update chapter 15.1 Event Listener contacts of the documentation](https://trello.com/c/nYpEfH61/13-update-chapter-151-event-listener-contacts-of-the-documentation)

**Comment by DanielChappuis** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improve Event Listener events](https://trello.com/c/CrJzu5TW/15-improve-event-listener-events)

**Comment by bolom009** [comment]
Hello guys :) Any updates here?)

**Comment by DanielChappuis** [comment]
I am currently working on this. This will be released in the next version of the library (v0.8.0) which will be released in April or May hopefully.

**Comment by bolom009** [comment]
Great job! Thanks for your work! I translating your code from c++ to golang. I hope version 0.8.0 will finished successful :)

**Comment by bolom009** [comment]
As for me your code realy awesome :) Easy read, good structure :)

**Comment by DanielChappuis** [comment]
Thanks for your feedback !

**Comment by bolom009** [comment]
@DanielChappuis do you have patreon or something else? :)

**Comment by DanielChappuis** [comment]
For the moment, I have [this ](https://reactphysics3d.com/donate.html)but I am working on the setup of Github Sponsors.

**Comment by DanielChappuis** [comment]
The version v0.8.0 of ReactPhysics3D has been released.

In this version, it is now possible to set colliders has being triggers. Moreover, using the EventListener class it is now possible to receive notifications when contacts occurs or when a collider overlaps with a trigger collider. You can find more information in the user manual [here](https://reactphysics3d.com/usermanual.html#x1-8300015).

Note that this version contains some public API changes. Please read carefully the change log before upgrading to this new version and do not hesitate to take a look at the user manual.

I am therefore closing this issue.
