### ISSUE TITLE
Implementation in header files

### ISSUE THREAD

**Issue by Reeley** [DanielChappuis/reactphysics3d#67]
Hey i just fiddled around with your library and its a really nice piece of software you created.

I have a problem including the reactphysics3d.h file into my headers though, i get a lot of errors when doing this. I guess this happens because the header files also contain implementations. Correct me if im wrong i just started with c++ again. When i include reactphysics3d.h in my cpp file it works as expected.

Also is there a reason why the header files contain implementation and this is not split into the cpp files?

**Comment by DanielChappuis** [comment]
The headers only contain definitions for the inline functions which is totally fine.

What kind of compilation errors do you have when you include the reactphysics3d.h header in your headers ?

**Comment by Reeley** [comment]
Okey i just created a new clean project and it works there. No idea why it doesnt in my other project.
These are the errors i get, but they are basically meaningless. At least for me:
https://i.imgur.com/FOR2sFP.png

**Comment by DanielChappuis** [comment]
I am glad that you managed to solve your issue.
Best regards
