### ISSUE TITLE
Raycasting which starts and ends in the same rigid body

### ISSUE THREAD

**Issue by andreasdr** [DanielChappuis/reactphysics3d#75]
Hi

I determine interaction objects in the world by doing ray casting.

See here
- https://github.com/andreasdr/tdme2/blob/master/src/tdme/engine/physics/World.cpp#L324

I have a special case where I do a ray cast that starts within a rigid body and ends within it. In this case the raycasting is not successful. 

Is this the expected behaviour or even handled like that by intention?

I can fix this in our game by adjusting the rigid body. So this is no big issue. I still wanted to ask about this.

Many thanx and

Best regards
Andreas

**Comment by DanielChappuis** [comment]
Hello,

Yes, this is the expected behavior. Ray casting only works from the outside of bodies. If the origin of a ray is inside a collision shape, not hit will be reported for that shape.

I have just added a note in the documentation for the next release to make this more clear.

Best regards
