### ISSUE TITLE
 using bodyindex = luint wanted or a mistake ?

### ISSUE THREAD

**Issue by DJLinux** [DanielChappuis/reactphysics3d#76]
(sorry about my bad English)

I use my reactphysics3d c wrapper for FreeBASIC on ARM 32/64-bit, Win32/64 and Linux32/64

It locks like  bodyindex should be size_t (unsigned 32 bit on 32bit OS and unsigned 64bit on 64Bit OS)

But bodyindex are defined as long unsigned int !
```
using luint = long unsigned int;
using bodyindex luint;
using bodyindexpair = Pair<bodyindex, bodyindex>; 
``` 
you know "long unsigned int" is:
32 bit on ARM32, Linux X86 and Windows X86
64-bit on ARM64 and Linux X86_64
**!!! but only 32bit on Windows X86_64 !!!**

I don't use Visual Studio I use on all platforms Code::Blocks with GNU c++ compilers.

Is that wanted or a mistake ?

By the way thank you for this nice library.

DJ

**Comment by DanielChappuis** [comment]
Hello,

Thanks a lot for your feedback. I was using "long unsigned int" to have a least 32 bits for the bodyindex because I thing that 4,294,967,295 bodies is more than enough. But I think I should use the type "uint32_t" instead to always have a 32 bits value even on 64 bits machine.

**Comment by DJLinux** [comment]
The fastest integer datatype are the the native size 32/64 bit
So for unsigned stuff size_t  are the first choice for me.
loop counters are size_t
array indexes are size_t
...
I changes all enum class defs to size_t also.
enum class XYZ : size_t {AAA, BBB, CCC}

By the way why do you not create a forum on your reactphysics3d.com site ?
Most coders that will use a physics lib select one with a community support forum.

Looks like git hub is the right place for questions or improvements of the source code
but not the usage of the react physics 3d library it self.

I self created a stable vehicle car class for TrueAxis (long time my favorite physics lib) 
Take a look if you like.  
500 cars in real time: https://www.youtube.com/watch?v=aJvW320mdZg
Jump baby jump: https://www.youtube.com/watch?v=2ZuWuokSJDQ

But TrueAxis is closed source so I never published my (hacked) work and TrueAxis closed his forum also. 

Joshy

**Comment by DanielChappuis** [comment]
The version v0.8.0 of ReactPhysics3D has been released. In this version, the bodyindexpair type is now a pair of Entity type. Therefore, this issue doesn't really apply anymore.

I am therefore closing this issue.
