### ISSUE TITLE
Suggestion for soft-body physics: ShapeOp

### ISSUE THREAD

**Issue by ColinGilbert** [DanielChappuis/reactphysics3d#8]
I have found an interesting toolkit that should run very quickly and accurately and its API is quite nice.

http://shapeop.org/

It's a rather easy to use constraint solver with a tidy API. It's got a brief example and the code is self-documenting. It's MPL-licensed, which seems quite reasonable. Also of interest might be http://www.gecode.org/ but its far bigger and more full-featured and it can be somewhat difficult to grasp. However, its MIT-licensed and also offers far more features (not necessarily limited to topology and physics sim) and volumes of documentation.

I would be up for collaboration in mid-July.

**Comment by ColinGilbert** [comment]
I must close as I recently discovered that it requires the LGPL'ed Cholesky solver from Eigen.

**Comment by DanielChappuis** [comment]
Thanks by the way. This library has been written by the lab where I did my master thesis :)
