### ISSUE TITLE
HeightFieldShape causing crash. Bug or my fault?

### ISSUE THREAD

**Issue by Martinusius** [DanielChappuis/reactphysics3d#80]
So I am creating a terrain and now i wanted to make it collide with other objects (bodies). This is my code for creating the HeightFieldShape (it's construstor for my TerrainTile class):
`		TerrainTile(int x, int z, rp3d::RigidBody* body)
			: m_X(x), m_Z(z), m_Heights(&(*generateGetHeights(46464))[0]), m_RigidBody(body),
			m_Shape(new rp3d::HeightFieldShape(512, 512, -250, 130, m_Heights, rp3d::HeightFieldShape::HeightDataType::HEIGHT_FLOAT_TYPE, 1, 1, rp3d::Vector3(1.5625, 1, 1.5625))),
			position(m_X * 800, 0, m_Z * 800) {
			m_ProxyShape = m_RigidBody->addCollisionShape(m_Shape, rp3d::Transform(rp3d::Vector3(0, -60, 0), rp3d::Quaternion::identity()), 1000);
			m_RigidBody->setType(rp3d::BodyType::STATIC);
		}`
(Sorry if the code looks a bit weird, I am using github for the first time.)

Okay, so when I update the dynamics world and some object (body) collides with the terrain my application crashes with this error: "Access violation reading location 0x000A3B0C."

Some things I already checked:
I tried SphereShape and BoxShape and they both worked how they should. 
The float array pointer contains 262144 (512 * 512) floats which should be enough for the HeightFieldShape.
None of the floats is higher than 130 (max value) or lower than -250 (min value).

Some additional info (related to my stuff, probably not important):
There is other class which contains the dynamics world and provides a rigidBody for this class .
generateGetHeights method returns vector that is then converted to float array pointer, 46464 is seed.

Sorry if my english is bad, I am not from english speaking country.

**Comment by Martinusius** [comment]
Solved it! Looks like the pointer was for some reason not saved into the variable.

**Comment by DanielChappuis** [comment]
Ok perfect. Sorry I did not have the time to look at it until today.
