### ISSUE TITLE
setFrictionCoefficient different from zero produce weird behaviour

### ISSUE THREAD

**Issue by aliasdevelopment** [DanielChappuis/reactphysics3d#85]
Hi Daniel

I have got a test scene where some boxes and spheres are generated using an initial velocity This works and I can see that these objects slide, jump and bounces, but with one weird behavior.

If setFrictionCoefficient of the physics material is set to some non-zero value, then the objects does not behave as expected. The boxes slides consistently to the right of the initial velocity direction. The spheres makes some twist/jump on the initial impact and then settle on a rolling direction. 

If setFrictionCoefficient is set to zero, then boxes and spheres follows the velocity direction spot on.

These are the values I used for the rigid body and material:

phys_mat.setBounciness( 0.1f );
phys_mat.setRollingResistance( 0.2f );
phys_mat.setFrictionCoefficient( 0.2f  ); or phys_mat.setFrictionCoefficient( 0.0f  );
body->setLinearDamping( 0.1f );
body->setAngularDamping( 0.1f );

Test using c2aeda9e0aea37fcc233d6246c8621137faf3b97

**Comment by aliasdevelopment** [comment]
Created a capture where the setFrictionCoefficient is zero:

https://imagebin.ca/v/4U28kVwe5Qb8

**Comment by DanielChappuis** [comment]
I have fixed a bug with the friction constraint in the contact solver with the commit 117cbdafb7d60a52191887488ffd9795deaa02dd in the master branch. 

Could you please test if it fixes your issue ?

**Comment by aliasdevelopment** [comment]
I have tested 117cbda and it works as expected. Objects follow the initial velocity vector as expected.

**Comment by DanielChappuis** [comment]
Perfect. Thanks a lot for reporting this issue.
