### ISSUE TITLE
Creating Linked List - Contact Manifold

### ISSUE THREAD

**Issue by ljohnson781** [DanielChappuis/reactphysics3d#89]
Hi,
I am trying to create a linked list of all the contact manifold points using your documentation:

`//add contact manifold to the linked list, IF the two shapes overlap (aabb check)
rp3d::List<const rp3d::ContactManifold*> manifolds;`
    
`// Get all the contacts of the world
manifolds = dynamicsWorld->getContactsList();
rp3d::List<const rp3d::ContactManifold*>::iterator it;`
    
`// For each contact manifold
for (it = manifolds.begin(); it != manifolds.end(); ++it) {
    const rp3d::ContactManifold* manifold = *it;`

but my team and I are running into an error at this piece: 

 `error: ‘iterator’ is not a member of ‘reactphysics3d::List<const reactphysics3d::ContactManifold*>’`

         `rp3d::List<const rp3d::ContactManifold*>::iterator it;`

Any help would be great!

**Comment by ljohnson781** [comment]
There is also a list error which I forgot to include in the original question: 

`error: no matching function for call to ‘reactphysics3d::List<const reactphysics3d::ContactManifold*>::List()’

         rp3d::List<const rp3d::ContactManifold*> manifold;`

**Comment by DanielChappuis** [comment]
Hello,

Sorry, I have just seen that the online documentation for retrieving contacts is not really up to date.

The first error you have is because the iterator class for the rp3d::List is called **Iterator** (with capital I) and not **iterator**.

`rp3d::List<const rp3d::ContactManifold*>::Iterator it`

The second error is because there is no default constructor for the class rp3d::List. This class takes a memory allocator in the constructor but you shouln't need to construct one to retrieve contacts.

Here is an example of how to retrieve contacts:

```
// Get the list of contact manifolds from the world
rp3d::List<const rp3d::ContactManifold*> manifolds = world->getContactsList();

// For each contact manifold
rp3d::List<const rp3d::ContactManifold*>::Iterator it;
for (it = manifolds.begin(); it != manifolds.end(); ++it) {

        const rp3d::ContactManifold* manifold = *it;

        // For each contact point of the manifold
        rp3d::ContactPoint* contactPoint = manifold->getContactPoints();
        while (contactPoint != nullptr) {

            rp3d::Vector3 point = manifold->getShape1()->getLocalToWorldTransform() * contactPoint->getLocalPointOnShape1();
			rp3d::Vector3 normalWorld = contactPoint->getNormal();
			openglframework::Vector3 normal = openglframework::Vector3(normalWorld.x, normalWorld.y, normalWorld.z);

            contactPoint = contactPoint->getNext();
        }
}

```
I hope this helps.

**Comment by DanielChappuis** [comment]
Can I close this issue ?

**Comment by ljohnson781** [comment]
Unfortunately no - there is still an error that occurs when trying to populate the contact manifold list. 

The Iterator vs iterator issue is fixed, though!

**Comment by ljohnson781** [comment]
`//return true if two broadphase collision shapes are overlapping
if (braodphase -> testOverlappingShapes(proxy1, proxy2)){
    //rp3d::ContactManifold * contact = new rp3d::ContactManifold();
    //rp3d::List<const rp3d::ContactManifold*> manifolds;
    auto manifolds = mDWorld->getContactsList();
    rp3d::List<const rp3d::ContactManifold*>::Iterator it;

    for(it = manifolds.begin(); it != manifolds.end(); it++){
        const rp3d::ContactManifold* manifold = *it;

        rp3d::ContactPoint* contactPoint = manifold->getContactPoints();
        while (contactPoint != nullptr){
            //retrieve the world points
            rp3d::Vector3 worldPoint1 = proxy1->getLocalToWorldTransform()
            rp3d::Vector3 worldPoint2 = proxy2->getLocalWorldTransform()
            contactPoint = contactPoint->getNext();
        }
        //rp3d::DynamicAABBTreeOverlapCallback callback;
        //mDetectionTree->reportAllShapesOverlappingWithAABB(proxy1->getWorldAABB(), &callback);
        //mDetectionTree->reportAllShapesOverlappingWithAABB(proxy2->getWorldAABB(), &callback);
    }
    //rp3d::EventListener listen = new rp3d::EventListener();
}`

above is a piece of our code, it will return true (overlapping), but won't get the manifolds. 
It seems like the issue exists within getContactPoints from the dynamic world

**Comment by DanielChappuis** [comment]
I am not sure I understand what you are trying to do. 

When you do:

`broadphase -> testOverlappingShapes(proxy1, proxy2)`

Are you working on internal objects inside the library ? I mean, the broadphase is not exposed to the users of the library.

If testOverlappingShapes() returns true, it means that broad-phase shapes (AABB) are overlapping but it does not mean there are contact points. The AABB of two objects might overlap even if the two collision shapes do not collide.

Maybe what you want is the CollisionWorld.testCollision() methods.

**Comment by ljohnson781** [comment]
`float vertices1[15];

    vertices1[0] = 4.0; vertices1[1] = 4.0; vertices1[2] = 9.0;

    vertices1[3] = 0.0; vertices1[4] = 8.0; vertices1[5] = 0.0;

    vertices1[6] = 0.0; vertices1[7] = 0.0; vertices1[8] = 0.0;

    vertices1[9] = 8.0; vertices1[10] = 0.0; vertices1[11] = 0.0;

    vertices1[12] = 8.0; vertices1[13] = 8.0; vertices1[14] = 0.0;


 


    int indices1[16];

    indices1[0] = 0; indices1[1] = 1; indices1[2] = 2;

    indices1[3] = 0; indices1[4] = 2; indices1[5] = 3;

    indices1[6] = 0; indices1[7] = 3; indices1[8] = 4;

    indices1[9] = 0; indices1[10] = 4; indices1[11] = 1;

    indices1[12] = 4; indices1[13] = 3; indices1[14] = 2; indices1[15] = 1;


 


    rp3d::PolygonVertexArray::PolygonFace* polygonFaces1 = new rp3d::PolygonVertexArray::PolygonFace[5];

    rp3d::PolygonVertexArray::PolygonFace* face1 = polygonFaces1;


 




    for (int f = 0; f < 5; f++) {

        if (f != 4)

        {

            face1->indexBase = f * 3;

            face1->nbVertices = 3;

        }

        else

        {

            //std::cout << "face is 4" << std::endl;

            face1->indexBase = f * 3;

            face1->nbVertices = 4;

        }

        face1++;

    }


 


    //create the polygon vertex array

    rp3d::PolygonVertexArray* pva1 = new rp3d::PolygonVertexArray(5, vertices1, 3 * sizeof(float), indices1,

        sizeof(int), 5, polygonFaces1, rp3d::PolygonVertexArray::VertexDataType::VERTEX_FLOAT_TYPE,

        rp3d::PolygonVertexArray::IndexDataType::INDEX_INTEGER_TYPE);


 


    //create the polyhedron mesh

    rp3d::PolyhedronMesh* pMesh1 = new rp3d::PolyhedronMesh(pva1);

    std::cout << "polyhedron mesh1 created" << std::endl;


 


    rp3d::ConvexMeshShape* convexMesh1 = new rp3d::ConvexMeshShape(pMesh1);

    std::cout << "convex mesh1 created" << std::endl;


 




    float vertices2[15];

    vertices2[0] = 4.0; vertices2[1] = -3.0; vertices2[2] = 5.0;

    vertices2[3] = 0.0; vertices2[4] = 10.0; vertices2[5] = 2.0;

    vertices2[6] = 8.0; vertices2[7] = 10.0; vertices2[8] = 2.0;

    vertices2[9] = 8.0; vertices2[10] = 10.0; vertices2[11] = 6.0;

    vertices2[12] = 0.0; vertices2[13] = 10.0; vertices2[14] = 6.0;


 


    int indices2[16];

    indices2[0] = 0; indices2[1] = 1; indices2[2] = 2;

    indices2[3] = 0; indices2[4] = 2; indices2[5] = 3;

    indices2[6] = 0; indices2[7] = 3; indices2[8] = 4;

    indices2[9] = 0; indices2[10] = 4; indices2[11] = 1;

    indices2[12] = 4; indices2[13] = 3; indices2[14] = 2; indices2[15] = 1;


 


    rp3d::PolygonVertexArray::PolygonFace* polygonFaces2 = new rp3d::PolygonVertexArray::PolygonFace[5];

    rp3d::PolygonVertexArray::PolygonFace* face2 = polygonFaces2;


 




    for (int f = 0; f < 5; f++) {

        if (f != 4)

        {

            face2->indexBase = f * 3;

            face2->nbVertices = 3;

        }

        else

        {

            //std::cout << "face is 4" << std::endl;

            face2->indexBase = f * 3;

            face2->nbVertices = 4;

        }

        face2++;

    }


 


    //create the polygon vertex array

    rp3d::PolygonVertexArray* pva2 = new rp3d::PolygonVertexArray(5, vertices2, 3 * sizeof(float), indices2,

        sizeof(int), 5, polygonFaces2, rp3d::PolygonVertexArray::VertexDataType::VERTEX_FLOAT_TYPE,

        rp3d::PolygonVertexArray::IndexDataType::INDEX_INTEGER_TYPE);


 


    //create the polyhedron mesh

    rp3d::PolyhedronMesh* pMesh2 = new rp3d::PolyhedronMesh(pva2);

    std::cout << "polyhedron mesh2 created" << std::endl;


 


    rp3d::ConvexMeshShape* convexMesh2 = new rp3d::ConvexMeshShape(pMesh2);

    std::cout << "convex mesh2 created" << std::endl;


 


    /********************************************************************************/


 




    rp3d::WorldSettings* settings = new rp3d::WorldSettings();

    std::vector<rp3d::ProxyShape*> proxyShapes;

    rp3d::Vector3  gravity(0, 0, 0);


 


    rp3d::Transform transform = rp3d::Transform::identity();

    rp3d::CollisionWorld* mWorld = new rp3d::CollisionWorld(*settings);

    rp3d::DynamicsWorld* dWorld = new rp3d::DynamicsWorld(gravity, *settings);


 


    rp3d::CollisionBody* body1 = mWorld->createCollisionBody(transform);

    std::cout << "added the body1 to the world" << std::endl;

    rp3d::CollisionBody* body2 = mWorld->createCollisionBody(transform);

    std::cout << "added the body2 to the world" << std::endl;


 




    rp3d::ProxyShape* proxy1 = body1->addCollisionShape(convexMesh1, transform);

    std::cout << "added shape1 to body1" << std::endl;

    rp3d::ProxyShape* proxy2 = body2->addCollisionShape(convexMesh2, transform);

    std::cout << "added shape2 to body2" << std::endl;

    //proxyShapes.push_back(proxy);


 


    rp3d::DynamicAABBTree* tree = new rp3d::DynamicAABBTree(rp3d::MemoryManager::getBaseAllocator(), 0.5);

    tree->addObject(body1->getAABB(), NULL);

    tree->addObject(body2->getAABB(), NULL);

    std::cout << "added bodies to tree" << std::endl;


 


    rp3d::MemoryManager mMemory = rp3d::MemoryManager();

    rp3d::ContactInfoMemoryAllocator a = rp3d::ContactInfoMemoryAllocator();

    rp3d::CollisionDetection* colDet = new rp3d::CollisionDetection(mWorld, mMemory);

    rp3d::BroadPhaseAlgorithm* broadphase = new rp3d::BroadPhaseAlgorithm(*colDet);

    std::cout << "made broadphase algorithm" << std::endl;


 


    broadphase->addProxyCollisionShape(proxy1, proxy1->getWorldAABB());

    broadphase->addProxyCollisionShape(proxy2, proxy2->getWorldAABB());

    std::cout << "added proxy collision shapes" << std::endl;


 


    bool test = broadphase->testOverlappingShapes(proxy1, proxy2);

    bool aabb = mWorld->testAABBOverlap(body1, body2);

    std::cout << "test is " << test << std::endl;

    std::cout << "aabb is " << aabb << std::endl;


 


    rp3d::ContactManifoldInfo* info = new rp3d::ContactManifoldInfo(a);

    rp3d::ContactManifold* man = new rp3d::ContactManifold(info, proxy1, proxy2, a, *settings);


 


    rp3d::List<const rp3d::ContactManifold*> manifolds = dWorld->getContactsList();

    rp3d::List<const rp3d::ContactManifold*>::Iterator it;

    for (it = manifolds.begin(); it != manifolds.end(); it++) {

        

        const rp3d::ContactManifold* manifold = *it;

        

        rp3d::ContactPoint* contactPoint = manifold->getContactPoints();

        

        while (contactPoint != nullptr) {


 


            rp3d::Vector3 worldPoint1 = manifold->getShape1()->getLocalToWorldTransform() * contactPoint->getLocalPointOnShape1();

            std::cout << "worldpoint1x is " << worldPoint1[0] << std::endl;

            std::cout << "worldpoint1y is " << worldPoint1[1] << std::endl;

            std::cout << "worldpoint1z is " << worldPoint1[2] << std::endl;


 


            rp3d::Vector3 worldPoint2 = manifold->getShape2()->getLocalToWorldTransform() * contactPoint->getLocalPointOnShape2();

            std::cout << "worldpoint2x is " << worldPoint1[0] << std::endl;

            std::cout << "worldpoint2y is " << worldPoint1[1] << std::endl;

            std::cout << "worldpoint2z is " << worldPoint1[2] << std::endl;

            contactPoint = contactPoint->getNext();

        }

    }


 




    return 0;

}`

**Comment by ljohnson781** [comment]
Above is our code - it creates two pyramids, one oriented sideways one vertical, and the goal is to get the contact points but the linkedList is empty. 
Both tests - testOverlappingShapes from broadphase and testAABBOverlap from collision world - are both true. The pyramids are clearly overlapping in the image created as well.
From what we can tell the issue is with **contactManifold** and **getContactsList**.

**Comment by DanielChappuis** [comment]
What exactly are you trying to do ?

You are not supposed to create a rp3d::DynamicAABBTree nor a rp3d::CollisionDetection, nor a rp3d::BroadPhaseAlgorithm object. I cannot help you if you use classes that are only supposed to be used internally inside the library. Those classes should not be used by users of the library.

If you want to detect collision between bodies but do not want to animate them, you first need to create a CollisionWorld, then add bodies into this world and finally use the CollisionWorld::testCollision() methods as described in the [user manual](https://www.reactphysics3d.com/usermanual.html) to know if the bodies are colliding and retrieve contact points.

**Comment by ljohnson781** [comment]
Thank you for clarifying that - our ultimate goal is to create shapes, see which ones overlap, and store them in a list. Then taking that list of overlapping shapes and getting the contact manifold points. 

Is it possible to do the above without utilizing the entire library? It seems like the possibility exists using the internal functions that I highlighted above. But we could be mistaken.

**Comment by DanielChappuis** [comment]
Yes it is possible. 

You do not have to use the internal classes of the library for that. First, you create a CollisionWorld. Then you create bodies (rp3d::CollisionBody) and add collision shapes to your bodies (rp3d::BoxShape, rp3d::SphereShape, rp3d::ConvexMeshShape, ...). Then, you simply need to use one of the CollisionWorld::testCollision() methods to get all the contact manifolds if collisions are found. The contact manifolds will contain the bodies in contact and the contact points.

In the testbed application that comes with the library, there is a CollisionScene demo where shapes are created into a CollisionWorld. The CollisionWorld::testCollision() method is used there to get the contact points and display them on the screen. Do not hesitate to take a look at the code [here](https://github.com/DanielChappuis/reactphysics3d/blob/master/testbed/scenes/collisiondetection/CollisionDetectionScene.cpp).

I hope this helps.

**Comment by ljohnson781** [comment]
Using the code example you linked, we now have further questions - 
The testbed successfully creates shapes, colors them, and makes them run into each other (using gravity and sleep, as well as the heightfield libraries). However this is not the goal of our project. 
The ultimate goal is what I stated above.
Will we need to create our own contact manager function in order to utilize **CollisionCallbackInfo** for the scope of our project?

**Comment by ljohnson781** [comment]
Hi Daniel - 

We are trying to get the contact points to print to the screen using ContactPointInfo (called by testCollision function - eventually it reaches where it creates the contact points), and then we tried another method to see if we got the same results using contactManager->getContactPoints but we get  different results. 

**first method:**
one point contact point info constructor info
point1 Vector3(6.875000,3.125000,5.312500)
point2 Vector3(3.125000,3.125000,3.812500)

one point contact point info constructor info
point1 Vector3(7.689655,7.689655,3.275862)
point2 Vector3(2.000000,7.689655,1.000000)

one point contact point info constructor info
point1 Vector3(7.689655,2.310345,3.275862)
point2 Vector3(2.000000,2.310345,1.000000)

**second method**: 7.68965 2.31034 3.27586
2 2.31034 1
7.68965 7.68966 3.27586
2 7.68966 1
6.875 3.125 5.3125
3.125 3.125 3.8125

**Which method should we use?**

**Comment by DanielChappuis** [comment]
Can I close this issue ?

**Comment by ljohnson781** [comment]
Yes, thank you for the help it’s much appreciated!

Lillian Johnson
Technologist
Booz l Allen l Hamilton
Johnson_Lillian@bah.com<mailto:Johnson_Lillian@bah.com>
