### ISSUE TITLE
Torque

### ISSUE THREAD

**Issue by KorolevSoftware** [DanielChappuis/reactphysics3d#90]
Hellow, I using your lib. I will face a problem. As I understand it, apply Torque applied to loocal space. If I set rp3d::Quaternion(0,0.5,0.5,1) to body and applay torque, I get the result( watch video)
[OpenCars .zip](https://github.com/DanielChappuis/reactphysics3d/files/3118183/OpenCars.zip)

**Comment by DanielChappuis** [comment]
Hello,

Actually, torque is applied in world-space using the RigidBody::applyTorque() method.

Can I ask you where did you see that it was applied in local-space ?

**Comment by KorolevSoftware** [comment]
I create body:
```C++
Vector3 initPosition(0.0, 5.0, 0.0);
Quaternion initRotate(0, 0.5, 0.5, 1);
Transform transform(initPosition, initRotate);

RigidBody* body;
body = world.createRigidBody(transform);
body->setType(BodyType::DYNAMIC);

BoxShape shapeBody(Vector3(2, 1, 1));

ProxyShape* proxyShapebody;
proxyShapebody = body->addCollisionShape(&shapeBody, Transform::identity(), 100);
proxyShapebody->setCollisionCategoryBits(CATEGORY2);
```
and applay Torque ```body->applyTorque(Vector3(0, -1000, 0));``` 
but, body rotate on Quaternion axis.

**Comment by DanielChappuis** [comment]
On my side, if I replace the line 133 in [this file](https://github.com/DanielChappuis/reactphysics3d/blob/master/testbed/scenes/cubes/CubesScene.cpp) in the "Cubes Scene" demo of the testbed application with the following code :

```
(*it)->setTransform(rp3d::Transform(position, rp3d::Quaternion(0, 0.5, 0.5, 1)));
(*it)->getRigidBody()->applyTorque(rp3d::Vector3(0, -1000, 0));
```

Everything look as expected, the bodies are rotating around the world Y axis and not around the local body axis.

**Comment by KorolevSoftware** [comment]
Hellow, I am sorry. It's my bug.  I did a wrong decomposition of the matrix. I store rotate by vec3(xEuler, yEuler, zEuler), position vec3(x, y, z). I wrong decomposition matrix of getOpenGLMatrix() to Euler angle. Sorry, sorry, sorry.
