### ISSUE TITLE
Convex polygon gets stuck/jibbles around

### ISSUE THREAD

**Issue by Paril** [DanielChappuis/reactphysics3d#92]
https://i.imgur.com/zQiGJUb.png

I'm not sure how to exactly explain this one, but I have a sample! 
[convexmesh.obj.txt](https://github.com/DanielChappuis/reactphysics3d/files/3193732/convexmesh.obj.txt)

With this obj file in the testbed, "Collision Shapes" shows the behavior. For some reason, some corners of the rectangle sink into the ground and/or slide. The mesh is convex and seems simple enough, not sure why it's exhibiting this behavior.

**Comment by DanielChappuis** [comment]
Hello,

This mesh has coplanar faces. As explained in the [documentation](https://www.reactphysics3d.com/usermanual.html), creating a convex mesh with coplanar faces should be avoided. A convex mesh should be created with the minimum number of faces. In your case, it should be a convex mesh with 6 quad faces and not 8 triangular faces. Actually this kind of shape should be created with a BoxShape and not a convex mesh.

I hope this helps.

**Comment by DanielChappuis** [comment]
Did you try with a mesh without any coplanar faces ? Can I close this issue ?

**Comment by Paril** [comment]
Ah I see. I must have skipped over that in my reading. I was triangulating meshes rather than using polygonal faces, so that'd explain why my convex models were messing up.
