### ISSUE TITLE
Question about the example of collision world in the documentation

### ISSUE THREAD

**Issue by sanghyunjoo1994** [DanielChappuis/reactphysics3d#94]
For the following example from the collision world

```
rp3d::WorldSettings settings ;
settings.nbVelocitySolverIterations = 20;
settings.isSleepingEnabled = false ;

// Create the world with your settings
rp3d::CollisionWorld world ( settings );
```
The compiler says
`class "reactphysics3d::WorldSettings" has no member "nbVelocitySolverIterations"`
What is wrong with this?
Also,  what is `rp3d::CollisionWorld world ( settings )`?
Is it a function? I am a little confused of how to use it.

Thank you

**Comment by DanielChappuis** [comment]
This code is not up to date in the user manual online. I will update it.

As you can see [here ](https://reactphysics3d.com/documentation/api/html/structreactphysics3d_1_1_world_settings.html)in the online API documentation, the **nbVelocitySolverIterations** variable is now called **defaultVelocitySolverNbIterations**. You should try to use a code completion tool on your IDE to prevent those issues in the future.

The following line:

`rp3d::CollisionWorld world ( settings );`

is simply a call to the constructor of the CollisionWorld class with the settings in parameter. If you do not understand this, I really suggest that you learn C++ first before diving into physics simulation.
