### ISSUE TITLE
Problem understanding how to get rigidbody updated rotation

### ISSUE THREAD

**Issue by ScrappyCocco** [DanielChappuis/reactphysics3d#97]
Dear Daniel,
I'm making a small game engine on my own to understand the basics of rendering.
I'm using your physics engine because is small and very easy to understand, but i have a problem, i am not able to get the rigidbody updated rotation.

I saw the rotation is managed using quaternions, so i tried to convert it to vector doing something like:
```cpp
const rp3d::Quaternion& rot = other.getOrientation();
const glm::quat glm_quat(rot.w, rot.x, rot.y, rot.z);
const glm::vec3 euler = glm::eulerAngles(glm_quat);

return_trasform.set_rotation(Core::SVector3(euler.x, euler.y, euler.z));
```

Unluckly, this doesn't seems to work.
In my test scene there's a "terrain" and a ball; the ball is made with a rigidbody and a Sphere proxy collision with radius `10.f` and mass `5.f`
I apply a force to the sphere using keyboard arrows, and calling `applyForceToCenterOfMass`.
The sphere, doesn't seems to get the correct rotation, as you can see [in this small example video](https://streamable.com/butv5).
The log print every frame the value of `return_trasform.rotation`, that as you can see it goes from -2 to 2.

Do you have any idea of what could be the problem?
Is a problem of conversion? Is the ball slipping on the ground instead of rotating on it?

I decided to write to you because right now i have no idea of what could cause this
Thank you for your time

**Comment by DanielChappuis** [comment]
Hello,

The sphere is supposed to roll (rotate) on your plane and not slip in your configuration. Could you post the values of the orientation quaternion during the animation ?

Make sure you didn't set the friction coefficient of one of your bodies to zero because of course in this case the sphere will slip and not roll.

Also be careful with angle units. Check if your function that you didn't mix degrees with radians.

**Comment by ScrappyCocco** [comment]
Both the ball and the cube under it have friction coefficient of 100 (there's a test print at the beginning)
I made you an updated video that you can see [here](https://streamable.com/w7xth), with the orientation quaternion print
In case you want to see the code that print it is:
```cpp
const rp3d::Quaternion& rot = other.getOrientation();
const glm::quat glm_quat(rot.w, rot.x, rot.y, rot.z);
const glm::vec3 euler = glm::eulerAngles(glm_quat);
	
Debug::DebugLog::print_to_console_log("rigidbody.getOrientation() - (x-y-z-w):");
Debug::DebugLog::print_to_console_log(
	std::to_string(rot.x) + " - " + 
	std::to_string(rot.y) + " - " + 
	std::to_string(rot.z) + " - " + 
	std::to_string(rot.w));

return_trasform.set_rotation(Core::SVector3(euler.x, euler.y, euler.z));
Debug::DebugLog::print_to_console_log("return_tras.get_rotation():");
Debug::DebugLog::print_to_console_log(return_tras.get_rotation());
```
To help you i copied all the console log in the file attached here:
[ConsoleLogText.txt](https://github.com/DanielChappuis/reactphysics3d/files/3331041/ConsoleLogText.txt)

Please let me know if you find out what's wrong with it
Thank you so much for your help

**Comment by DanielChappuis** [comment]
Sorry but I see nothing wrong with the quaternion values. The physics ball seems to be rotating.
Maybe try rotating the sphere with your code by manually setting the values to the set_rotation() method to see if this method is correctly working and if the values you use are correct.

Please, do not use 100 as friction coefficient. This seems very large. Try with the default friction coefficient.

Enabling the logs or ReactPhysics3D won't really help.

**Comment by ScrappyCocco** [comment]
Yes, it was a conversion problem using euler angles, it's my fault
I should do more stuff with quaternions, thanks for your help and sorry
