### ISSUE TITLE
CollisionWorld::mNbWorlds is never decremented wanted or a mistake ?

### ISSUE THREAD

**Issue by DJLinux** [DanielChappuis/reactphysics3d#98]
(sorry about my bad English)
Hello Daniel , 
the static member CollisionWorld::mNbWorlds is never decremented in the destructor
is it wanted or a mistake ?

By the way thanks for the fixes in 0.7.1
I had only changed bodyindex to uint for the FreeBASIC 32/64-bit C wrapper.

How ever good job so far.
DJ

**Comment by DJLinux** [comment]
I see isn't important you use mNbWorlds only to build mName if not given.
DJ

**Comment by DanielChappuis** [comment]
Yes it's only used in the logs and it's correct not to decrement it in the destructor.
