### ISSUE TITLE
How to update proxy shape of a collision body?

### ISSUE THREAD

**Issue by st585** [DanielChappuis/reactphysics3d#99]
Hi,

We are using the rp3d physics engine to perform collision detection and keep track of AABB tree, but we aren't utilizing the engine's movement capability as the data we are using is read in from an external source.

We read in the data, create ConvexMeshShapes and add the proxy shape to collision bodies, and test collision. In the next frame, we would like to update those collision bodies with proxy shapes in new locations, but not use the engine to move the shapes as we don't know what direction or how the shapes will be moving beforehand.

Would it be possible to simply replace the proxy shape in the CollisionBody with the new proxy shape, or is it more involved to manually move the Collision Body?

Thank you so much!

**Comment by DanielChappuis** [comment]
Hello,

If the collision shapes of your ProxyShapes do not change between frames but only move, I think you can simply move the ProxyShapes within the local-space of the CollisionBody using the ProxyShape::setLocalToBodyTransform(). If the ProxyShapes do not move within the local-space of the CollisionBody but it's only the CollisionBody that moves within world-space, you can use the CollisionBody::setTransform() method to move the whole CollisionBody (with all the ProxyShapes inside it).

I hope it answers your question.

**Comment by st585** [comment]
Yes that answers my question! Thank you so much!

**Comment by DanielChappuis** [comment]
No problem. Good luck with your project.
